### ISSUE TITLE
Custom tools: TypeError in start_background_check()

### ISSUE THREAD

**Issue by BayerSe** [jaap-karssenberg/zim-desktop-wiki#1]
Hi,

I am using a script which I use to jump to a certain page using xdotool. I call this script via the custom tools.

Since 0.66 I see the following message when I click the button:

	This is zim 0.66
	Platform: posix
	Locale: en_US UTF-8
	FS encoding: UTF-8
	Python: (2, 7, 13, 'final', 0)
	Gtk: (2, 24, 31)
	Pygtk: (2, 24, 0)
	Zim revision is:
	  branch: zim-trunk
	  revision: 871 jaap.karssenberg@gmail.com-20170428103155-0xaqvtl2g53epq2y
	  date: 2017-04-28 12:31:55 +0200

	======= Traceback =======
	  File "/usr/lib/python2.7/site-packages/zim/gui/__init__.py", line 1624, in _exec_custom_tool
	    self.notebook.index.start_background_check()
	TypeError: start_background_check() takes exactly 2 arguments (1 given)

**Comment by BayerSe** [comment]
Looking at the code of `zim-desktop-wiki/zim/gui/__init__.py` I found:

    410  - self.notebook.index.start_background_check(self.notebook)
    1624 - self.notebook.index.start_background_check()

So, could that missing `self.notebook` be the issue?

**Comment by jaap-karssenberg** [comment]
Patch committed in 0dd595bf46fdaf629faac9c6d59f1ca7858a2d41
