### ISSUE TITLE
Page suggestions do not always work in 0.66

### ISSUE THREAD

**Issue by nasedil** [jaap-karssenberg/zim-desktop-wiki#10]
In the new 0.66 release page suggestions (when jumping or inserting a link) do not behave like before.  When choosing some page, and then inserting a colon, it does not show child pages suggestions anymore.  After clicking 'rebuild index' it starts to work, but later it doesn't work again.

**Comment by jaap-karssenberg** [comment]
Path in 0c55e97f79d8d7465065408d3b133a5d6a654104
