### ISSUE TITLE
It takes 2 clicks to open another page after editing

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#103]
If you write something in a page and want to open another one, by clicking on it in the index side pane, then you have to click twice on a page. If a page wasn't edited before, then only one left click is enough.

Happens on the latest v0.66 from the snapshots ppa under Ubuntu Gnome 17.04.

**Comment by vossenjp** [comment]
Something like this is still happening in 0.70, and has been for a while for me.  0.66 seems about right, actually.  I was going to open a bug with "ToC needs 2-3 clicks to register" or "It seems to take 2-3 clicks in the ToC to have any effect to jump around to headers" or similar...

**Comment by vossenjp** [comment]
This is still happening in 0.73.2, but only in large notebooks with large/long pages on older hardware (1-2 CPU).  It's a constant (low-level) frustration with my Work Zim notebook (which I can't share) running on a 2 CPU VM living on top f Windows, and I can't reproduce it in a minimal notebook.
