### ISSUE TITLE
Edit Source fails in Windows

### ISSUE THREAD

**Issue by bkidwell** [jaap-karssenberg/zim-desktop-wiki#105]
Version: 0.67-rc2 -- run from source or from built release package.

Open any page and click Tools → Edit Source. You get an error:

    No such file or folder: C:\Users\vmuser\Notebooks\Notes\Home.txt

On my work machine it also didn't like my "notepad2-usercreated.desktop" that I'd created long ago. I tried putting different values in the Exec field of that file and nothing worked.

[debug.log.txt](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/1070500/debug.log.txt)

**Comment by bkidwell** [comment]
Hmm... Problem seems to have gone away when I deleted the .desktop file and used Edit Source to get prompted to create a new one.

**Comment by bkidwell** [comment]
It's currently working when I run it from source but not from the .exe build. Sorry for the many replies.

[debug log from exe build.txt](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/1070524/debug.log.from.exe.build.txt)

What does anyone make of this?

**Comment by bkidwell** [comment]
applications.py hasn't changed since 2016. This failure has to be a new problem in the Windows build process, somehow.

**Comment by mnordlin** [comment]
As there has been no developments in a week, I wanted to ask @bkidwell whether the problem is resolved by now. I just tested your excellent Release Candidate 2 installer binary, and NPP opened just fine.

**Comment by jaap-karssenberg** [comment]
Looks like two separate issues:
- for the first "No such file or folder" I can't deduce what happened here.
- for the second the GError occurs in the spawn method, from the log message looks like arguments provided by zim make sense, so apparently in build process something is missing that is required by the spawn function to work ?

**Comment by bkidwell** [comment]
Sorry I forgot to mark this as resolved in 0.67-rc2-win-2, from 17 June.
