### ISSUE TITLE
Documentation is not updated with new features

### ISSUE THREAD

**Issue by nasedil** [jaap-karssenberg/zim-desktop-wiki#11]
A couple of new features were noted in 0.66 release notes but they were not documented in help (like 'move' checkbox state and how to ender a horizontal line).

I think it could be a good idea to include new feature tips for every version in help (or link to changed pages of documentation)

**Comment by jaap-karssenberg** [comment]
Could you provide the content  to update in the manual? E.g. as a patch to the manual notebook, or manual text files as attachment?

**Comment by nasedil** [comment]
@jaap-karssenberg yes I will do that.  I'm going through the mailing list now and will put relevant info into the docs.
