### ISSUE TITLE
task list: make "only show active tasks" sticky

### ISSUE THREAD

**Issue by reagle** [jaap-karssenberg/zim-desktop-wiki#115]
I would like that option to persist across invocations of the plug in.

**Comment by jaap-karssenberg** [comment]
Testing in 67-rc2 and seems to me that filter is remembered correctly

**Comment by reagle** [comment]
Yes, that is what I am using too. BTW: Is it supposed to be remembered across instances of zim? If that is the case (and that would be handy) I could see if the configuration file changes...

**Comment by jaap-karssenberg** [comment]
Yes. What I observe is:
1. I change the filter in the context menu (either side pane view or dialog)
2. Quit zim with Ctrl-Q
3. Start again for same notebook
4. Check context menu again --> same setting active

You should see the "state.conf" in the notebook cache folder change. There is a key "only_show_act" under the section for the tasklist widget.

**Comment by reagle** [comment]
- how do you "only show active" when using the sidepane? I can type in text to filter, but don't see a check box.
- I did not see any changes to `state.conf`, but I had lots of versions in my file system. I tried editing `state.conf` manually, turning `False` to `True`, but that had no effect.
- Thinking I was editing the wrong one, I deleted all of the `state.conf` files I could find. Now when I open zim, it does not remember its place nor size, nor are there any new `state.conf` files created.

I do have a new index in my cache directory:
```
╭─reagle@hom ~/.cache/zim/notebook-Users_reagle_joseph_plan_zim
╰─➤  dir
total 180
-rw-r--r-- 1 reagle staff 184320 2017-07-05 11:38 index.db
```

**Comment by reagle** [comment]
Running it again today, I now have a state.conf and determined:

1. Setting `only_show_act=True` in `[TaskListSidePane]` **does** suppress inactive tasks. But I don't see a way to toggle this in the side pane...?
2. `[TaskListPlugin]` has no attributes, if I add `only_show_act=True` nothing changes in the plugin. Toggling the checklist has no effect on state.conf and does not persist.

**Comment by jaap-karssenberg** [comment]
@reagle see my earlier comment, you can toggle it using the "context menu", this is the menu that pops up on right-mouse-click

Should be no need to modify the `state.conf` file, zim writes it on close. Tested again with 0.67-rc2 and works for me every time.  If it doesn't work for you, run zim with `--debug` from the command line and check for errors when zim tries to write the `state.conf` file.

Be aware that state is written on events like explicit "quit" - not every time you toggle the switch

    DEBUG: Action: quit
    DEBUG: Remove window: StatusIconTrayIcon
    DEBUG: Wrote C:\my\home\Notes\.zim\state.conf

**Comment by reagle** [comment]
Is this exception showing the write failed?
```
DEBUG: Action: quit
DEBUG: Wrote /Users/reagle/.cache/zim/notebook-Users_reagle_joseph_plan_zim/state.conf
/Users/reagle/bin/zim-desktop-wiki-0.67-rc2/zim/gui/__init__.py:1902: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  Window.destroy(self) # gtk destroy & will also emit destroy signal
/Users/reagle/bin/zim-desktop-wiki-0.67-rc2/zim/plugins/__init__.py:783: GtkWarning: gtk_ui_manager_remove_action_group: assertion 'g_list_find (self->private_data->action_groups, action_group) != NULL' failed
  self.window.uimanager.remove_action_group(self.actiongroup)
DEBUG: Remove window: MainWindow
DEBUG: Last toplevel destroyed, quit
```

**Comment by reagle** [comment]
Here I am trying to create the sitting on the plugin, note the debugs:
```
DEBUG: Action: show_task_list
WARNING: Invalid config value for sort_order: "<enum GTK_SORT_ASCENDING of type GtkSortType>" - Must be integer
DEBUG: Opening dialog "Task List - Zim"
/Users/reagle/bin/zim-desktop-wiki-0.67-rc2/zim/plugins/__init__.py:815: GtkWarning: gtk_container_remove: assertion 'GTK_IS_TOOLBAR (container) || widget->parent == GTK_WIDGET (container)' failed
  self.window.action_area.remove(b)
DEBUG: Closed dialog "Task List"
DEBUG: Action: quit
DEBUG: Wrote /Users/reagle/.cache/zim/notebook-Users_reagle_joseph_plan_zim/state.conf
/Users/reagle/bin/zim-desktop-wiki-0.67-rc2/zim/gui/__init__.py:1902: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  Window.destroy(self) # gtk destroy & will also emit destroy signal
/Users/reagle/bin/zim-desktop-wiki-0.67-rc2/zim/plugins/__init__.py:783: GtkWarning: gtk_ui_manager_remove_action_group: assertion 'g_list_find (self->private_data->action_groups, action_group) != NULL' failed
  self.window.uimanager.remove_action_group(self.actiongroup)
DEBUG: Remove window: MainWindow
DEBUG: Last toplevel destroyed, quit
```

**Comment by jaap-karssenberg** [comment]
Looks to me that the state.conf is written correctly, so it should reflect
the filter choices for the tasklist.

-- Jaap

**Comment by reagle** [comment]
`state.conf` might be a red herring because the "only show active tasks" does not even stick between instantiations of the plugin (i.e., open plugin, select the option, close it, open it again and the option is not clicked). This is all within the same run/process of a single zim.

If it isn't sticking in some data structure in memory, I'm not surprised it isn't written out on exit.

**Comment by reagle** [comment]
Again, setting the following in `state.conf` made no difference:
```
[TaskListPlugin]
only_show_act=True
```
Neither did changing lines 64 and 107 in `gui.py`
```
		self.uistate.setdefault('only_show_act', True)
```

**Comment by jaap-karssenberg** [comment]
Can't figure out at all why it would work for me but not for you. Can you
double check what version you are running?

**Comment by reagle** [comment]
Please see the [screengrab](http://reagle.org/joseph/tmp/zim-tasklist-capture.mp4) which shows you the bug, version number, and debug info.

**Comment by reagle** [comment]
Confirmed, thank you!
