### ISSUE TITLE
tasklist does not recognize dates if followed by punctuation

### ISSUE THREAD

**Issue by muguu** [jaap-karssenberg/zim-desktop-wiki#117]
Not sure if this is an issue:

I think the regex for parsing the start and due date does not find a date if
there is a period or comma at the end of the date

Regards,
Murat

**Comment by jaap-karssenberg** [comment]
You are right - it is the end of the pattern defined here https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/master/zim/plugins/tasklist/dates.py#L46

The `(?![\S])` means "nothing that isn't a whitespace" - probably the "`\b`" code  makes more sense here and would be more robust to punctuation.
