### ISSUE TITLE
zim --plugin quicknote input=stdin no longer copying content from standard input

### ISSUE THREAD

**Issue by rhertzog** [jaap-karssenberg/zim-desktop-wiki#123]
I use some code that does a call like this to record content from my mailer into my INBOX managed by zim:
```
echo "Hello" | zim --plugin quicknote "notebook=file:///home/rhertzog/Dropbox/Notes" "namespace=:Gestion de ma vie:Tâches:INBOX" input=stdin
```

With 0.67~r2 that code no longer works as expected. The window opens but its content is empty. When run, I also get a new output line:
```
INFO: This is zim 0.67-rc2
```

**Comment by Osndok** [comment]
That sounds like what I was just working on today!

After a cursor inspection of the quicknote plugin, I would say that you are probably effected by the same stale caching effect I worked around today. I was actually just working on this today!

To test this theory, try appending to a page that you **do-not-have-open**, and come back to it... see if it appended then.

**Comment by rhertzog** [comment]
The problem is not the content on the Zim page being modified. I immediately see the new content added on the page. The problem is that I don't see any content in the quicknote window itself even though I have sent content through standard input. But when I manually type my content in the window and validate, then my content is properly stored in zim.

**Comment by rhertzog** [comment]
Note that input=clipboard works fine. But not input=stdin.

**Comment by jaap-karssenberg** [comment]
Will investigate. The issue probably is that the command is dispatched to the main process before stdin is read. Then stdin of the main process is read, which will indeed by empty.
