### ISSUE TITLE
Custom tool bug

### ISSUE THREAD

**Issue by maxmv** [jaap-karssenberg/zim-desktop-wiki#135]
Custom tool --> command: focuswriter %f --> change page and save it in focuswriter --> close focuswriter --> bring dialog window "can't save page"
Sometimes with focuswriter %s

This is zim 0.67-rc2
Platform: posix
Locale: ru_UA UTF-8
FS encoding: UTF-8
Python: (2, 7, 13, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 1633, in _exec_custom_tool
    self.reload_page()
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 1168, in reload_page
    self.notebook.flush_page_cache(self.page)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/operations.py", line 365, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/notebook.py", line 466, in flush_page_cache
    assert not page.modified, 'BUG: Flushing page with unsaved changes'
AssertionError: BUG: Flushing page with unsaved changes

**Comment by sojusnik** [comment]
I also use Focuswriter, but never thought combining it with Zim. Can you elaborate on your use-case (Zim combined with Focuswriter) more detailed please?

**Comment by maxmv** [comment]
I write books. Focuswriter helps me do this in comfort with ZIM. 
-book Name (some text about it, due date, concept)
--book (text for book)
---chapter1
----some piece of text1 and todo in text marked with labels like LEARN:, EDIT:... 
----some piece of text2
----...
---chapter2
----some piece of text1
----...
--notes
--quotes
--files (articles and books that helps to me)
Custom tool "focuswriter %s" helped to me with write and edit "some piece of text1". Also i use daily goal in Focuswriter.

But now custom tool is too buggy.

**Comment by jaap-karssenberg** [comment]
- `save_changes()` should ensure background save finished
- `_exec_custom_tool()` should call `save_changes()`
