### ISSUE TITLE
Paragraph spacing

### ISSUE THREAD

**Issue by maxmv** [jaap-karssenberg/zim-desktop-wiki#140]
Please add space between paragraphs.
**Now:**
 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis est quam, ut facilisis enim placerat non. Sed vestibulum, justo eget vestibulum eleifend, lacus nulla iaculis sem, imperdiet venenatis neque erat a nulla. Sed et felis in tellus mollis lobortis. Sed odio sem, rutrum eget gravida a, iaculis et ipsum. Vivamus mollis eros a dui gravida, vel tincidunt enim mollis. Nullam nibh urna, interdum vel neque ut, accumsan auctor lacus. Mauris ullamcorper venenatis risus, eget tristique mi euismod ac.
Curabitur sit amet justo a neque iaculis volutpat. Suspendisse sed metus leo. Sed tellus nisl, luctus quis placerat ac, eleifend quis nisl. Curabitur dignissim a urna in pulvinar. Morbi tempus sed tellus in maximus. Integer euismod diam facilisis dolor scelerisque, id vulputate dolor luctus. Aenean arcu massa, pulvinar vitae felis nec, posuere tincidunt dui. 
**After:**
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis est quam, ut facilisis enim placerat non. Sed vestibulum, justo eget vestibulum eleifend, lacus nulla iaculis sem, imperdiet venenatis neque erat a nulla. Sed et felis in tellus mollis lobortis. Sed odio sem, rutrum eget gravida a, iaculis et ipsum. Vivamus mollis eros a dui gravida, vel tincidunt enim mollis. Nullam nibh urna, interdum vel neque ut, accumsan auctor lacus. Mauris ullamcorper venenatis risus, eget tristique mi euismod ac.

Curabitur sit amet justo a neque iaculis volutpat. Suspendisse sed metus leo. Sed tellus nisl, luctus quis placerat ac, eleifend quis nisl. Curabitur dignissim a urna in pulvinar. Morbi tempus sed tellus in maximus. Integer euismod diam facilisis dolor scelerisque, id vulputate dolor luctus. Aenean arcu massa, pulvinar vitae felis nec, posuere tincidunt dui.

**Comment by sojusnik** [comment]
This is already possible with `linespacing` in the `~/.config/zim/style.conf`.

Try f.i.:

```
[TextView]
bullet_icon_size=GTK_ICON_SIZE_MENU
indent=30
tabs=None
linespacing=8
font=
justify=

```

There's also another related issue [here](https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/86).

**Comment by maxmv** [comment]
I don't understand how I'm lost this. Big thanks sojusnik!
This must be in GUI settings.

**Comment by sojusnik** [comment]
Not a big deal :) You find this kind of information in the Help Manual (press F1 in Zim).

Всех благ :+1:

**Comment by sojusnik** [comment]
Since your request was solved, could you kindly mark it as solved?
Thanks in advance!
