### ISSUE TITLE
"Ctrl+Home" doesn't move cursor to beginning of the text

### ISSUE THREAD

**Issue by gsidhu** [jaap-karssenberg/zim-desktop-wiki#148]
I just noticed that while pressing "Ctrl+End" takes you to the end of the text, the reverse command doesn't seem to work. It instead takes you to the beginning of the current line, which is what simply pressing the Home button does. Ctrl+Home should take you to the beginning of the first line of the text.

Of course it's not a deal breaking bug but it is something that power users might notice in their workflow.

**Comment by jaap-karssenberg** [comment]
This is a old bug that is already fixed in latest version(s)
