### ISSUE TITLE
another way to promote pages to the head of the pathbar queue (would be nice)

### ISSUE THREAD

**Issue by Osndok** [jaap-karssenberg/zim-desktop-wiki#156]
Sometimes, I find myself using the pathbar to switch to-and-from a page that slowly... "sunsets" (either behind the visible scroll region or off the pathbar entirely).

To my understanding, the only way to promote a page is by navigating to it by a non-pathbar means.

It would be nice to have another mechanism (whether implicit or explicit) that has this effect.

Perhaps:
* promote pages that are changed/saved, or
* have a 'push to front' option in the context menu

**Comment by Osndok** [comment]
Or perhaps... since they are already draggable... the order could simply be directly manipulated?

**Comment by jaap-karssenberg** [comment]
I think you are looking for the "REcently changed pages" pathbar mode - see the View -> Pathbar menu item

**Comment by Osndok** [comment]
Wonderful! Still finding more to love about Zim a the time!
