### ISSUE TITLE
Partial rendering of pages that contain code blocks

### ISSUE THREAD

**Issue by sakishrist** [jaap-karssenberg/zim-desktop-wiki#160]
Hello,

I am encountering this issue with version 0.67 on Linux Mint 18.2 (Based on Ubuntu 16.04).

When I open a page with code blocks, they are not rendered properly (they have missing formatting and numbers). Apart from that, the page does not respond (visually) to any interactions. The way to get the page to respond is to scroll (if the page is long enough) or to resize the window. When the pages starts responding again, it is evident that any actions I have done in it's non-responsive state have been applies (if I attempt to select a piece of text and press the delete button, nothing seems to happen but if I resize the window, I see the text now deleted.)

Unfortunately, no valuable information seems to be provided by the debug option:
```
INFO: Open page: OpenCode:Installation of 6 node cluster:02. OpenCode Components:04. OC Connectors (OpenCode:Installation of 6 node cluster:02. OpenCode Components:04. OC Connectors)
DEBUG: Insert object: <zim.plugins.sourceview.SourceViewObject object at 0x7f91ca413390>
DEBUG: Insert object: <zim.plugins.sourceview.SourceViewObject object at 0x7f91ca413650>
DEBUG: Insert object: <zim.plugins.sourceview.SourceViewObject object at 0x7f91cbffca10>
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
```

Best regards,
Sakis

**Comment by jaap-karssenberg** [comment]
Can you attach the text file source of a page that shows this behavior?

Need to be able to reproduce to understand what happens.

**Comment by sakishrist** [comment]
I don't see it happening anymore, although I am still with the same version.

It might have been some dependency.

I am closing for now. If it happens again, I'll re-open.
