### ISSUE TITLE
Zim doesn't work on macOS Sierra, so it gave Python errors on terminal.

### ISSUE THREAD

**Issue by gusbemacbe** [jaap-karssenberg/zim-desktop-wiki#165]
## Description

I followed @reagle's [trainings](http://reagle.org/joseph/zwiki/Archives/2015/Zim_on_Mac_OSX.html). And after trying to install pip install `pyenchant pyxdg pygtkspellcheck` and it gave Python errors on terminal.

## Versions
**Homebrew:** 1.2.4 and `Homebrew/homebrew-core`
**OS:** macOS Sierra 10.12.6
**PHP:** 7.1.7 (cli)
**Python:** 2.7.13 (linked) and 3.6.1 (unlinked)

## Observations

I prefer using PHP 7 and Python 3.

## Errors:

```
pip install pyenchant pyxdg pygtkspellcheck

Collecting pyenchant

  Downloading pyenchant-1.6.11-py2.py3.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp33.pp35-none-macosx_10_6_intel.macosx_10_9_intel.whl (4.8MB)

    100% |████████████████████████████████| 4.8MB 200kB/s 

Collecting pyxdg

  Downloading pyxdg-0.25.tar.gz (48kB)

    100% |████████████████████████████████| 51kB 4.7MB/s 

Collecting pygtkspellcheck

  Downloading pygtkspellcheck-4.0.5.tar.gz (167kB)

    100% |████████████████████████████████| 174kB 1.4MB/s 

    Complete output from command python setup.py egg_info:

    build_sphinx command is unavailable, please install Sphinx to solve this

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-p5IANX/pygtkspellcheck/setup.py", line 44, in <module>

        import gtkspellcheck

      File "/private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-p5IANX/pygtkspellcheck/src/gtkspellcheck/__init__.py", line 52, in <module>

        from gtkspellcheck.spellcheck import (SpellChecker, NoDictionariesFound,

      File "/private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-p5IANX/pygtkspellcheck/src/gtkspellcheck/spellcheck.py", line 26, in <module>

        import enchant

    ImportError: No module named enchant

    

    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-p5IANX/pygtkspellcheck/
```

**Comment by reagle** [comment]
Unfortunately, there is not an easy zim install for MacOS, but I am happy to try to help. I suspect the problem above is related to your path, as [discussed here](https://stackoverflow.com/questions/36137496/os-x-install-of-sphinx-the-sphinx-build-and-sphinx-quickstart-not-found).

Are you familiar with Python and homebrew? I think the thing to do is to try to install each dependency individually, and then go into the python interpreter and make sure you can import it.

**Comment by gusbemacbe** [comment]
Yes, I program and code Python because I am a computer science student, but my Pythin isn't complete yet. I used Homebrew since 2010 when I installed FontForge and GoldenDict via Homebrew, @reagle.

**Comment by reagle** [comment]
Okay, as I suggested you might have to reconfigure your paths (this pip thing has nothing to do with zim; its pip & mac/brew).

You could also try running zim, and see what that tells you.

```/usr/local/bin/python2 ~/bin/zim-0.67/zim.py```

**Comment by gusbemacbe** [comment]
It gave errors:

/usr/local/bin/python2 ~/bin/zim-0.67/zim.py
WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'
WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'

(process:10363): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

But it still worked to open Zim if then still with errors. 

![screen shot 2017-07-21 at 23 14 43](https://user-images.githubusercontent.com/2257024/28487598-6c614468-6e6a-11e7-96e4-57dcd77abd6a.png)

**Comment by reagle** [comment]
I wouldn't worry about the warnings, and I'm glad it worked. 

I think the dependencies I install are to get the spell checking working.

You may want to close this issue, and since this wasn't really about zim itself, it might be better to raise concerns on the email list.
