### ISSUE TITLE
Use of spellcheck crashes Zim when used with larger pages

### ISSUE THREAD

**Issue by ecodiv** [jaap-karssenberg/zim-desktop-wiki#166]
When enabling spellcheck with larger pages open, Zim zim crashed with signal 5 in PyEval_EvalFrameEx()

**Comment by jaap-karssenberg** [comment]
Can you add info on the zim version and the spellcheck dependencies you use (gtkspell or gtkspellcheck)?

Also would be helpfull to know how big, preferably by an example text file for a page that causes this.

Thanks

**Comment by ecodiv** [comment]
Hi Jaap, I am using ZIM 0.67, gtkspellcheck 3.0-1.1 (default version Ubuntu 160.4). I'll send you an example of a page with which ZIM crashes when the spellcheck is enabled by e-mail.

**Comment by jaap-karssenberg** [comment]
So far no crash while using python-gtkspellcheck 4.0.5-1 and the patch for #168

**Comment by jaap-karssenberg** [comment]
Closing this one for now.  Please open a new issue if similar problems are seen on the to be released zim 0.70 or newer.
