### ISSUE TITLE
instant crash when pasting or entering character to code block with syntax "defaults"

### ISSUE THREAD

**Issue by www-nanoscopic-de** [jaap-karssenberg/zim-desktop-wiki#170]
OS: Windows 10; zim 0.67 (not the portable one)
OS: Ubuntu 16.10; zim/yakkety,yakkety,now 0.65-3 all

I have a wiki page containing a code block with syntax set to "Defaults". If I paste a single character or even type a single character into the code block, zim crashes instantly (on both linux and windows).

On windows I get an error message:

Title: Microsoft Visual C++ Runtime Library
Message: Runtime Error!
Program: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe

This Application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

On linux started with -V option:
GtkSourceView:ERROR:gtksourcecontextengine.c:5903:update_syntax: assertion failed: (state->context != NULL)

**Comment by qyra** [comment]
I ran into this error as well, and did a bit more testing. It's definitely an upstream error in gtksourceview, and as far as I can tell there is nothing you could do in Zim itself to make the 'Defaults' language behave correctly.

This is a small code sample which normally just displays a textview for tutorial purposes. I modified it to always use the 'Defaults' language to see if I could make any changes that would make it work, but it crashes in the same way with any modifications I've tried so far. 
https://gist.githubusercontent.com/qyra/5baeebab70155050947ac7e793f02850/raw/7721b652edd746cf336963770db8f20219563c4c/test-widget.py

The easiest way to deal with this would be just removing Defaults from the language selection dialog for sourceview.

**Comment by jaap-karssenberg** [comment]
Closing as "Won't Fix" as this looks like an issue in the underlying library.

Zim will port to Gtk3 soon, hope that helps to pull in newer versions of the library
