### ISSUE TITLE
Two places for bugs on the homepage

### ISSUE THREAD

**Issue by hilbrichtsoftware** [jaap-karssenberg/zim-desktop-wiki#180]
On http://zim-wiki.org/manual/Bugs.html it says you should go to http://bugs.launchpad.net/zim. 

On http://zim-wiki.org/contact.html it says to go to github. 

Is this on purpose?

**Comment by rdft4e** [comment]
Dear  jaap-karssenberg,
I'm sorry, I was reporting a bug in the launchpad site. 
https://bugs.launchpad.net/zim/+bug/1701418
Do you want that I open an issue here in github?
