### ISSUE TITLE
Tiny checkboxes in HiDPI screen

### ISSUE THREAD

**Issue by nelas** [jaap-karssenberg/zim-desktop-wiki#181]
Checkboxes are tiny and hard to read in high-res screens on Ubuntu GNOME 17.04.

Left is the size proportion in a standard-res screen and right in a HiDPI screen (ignore font differences).
![checkboxes](https://user-images.githubusercontent.com/361179/29116451-186e81c8-7cfb-11e7-90a0-0b2d2c49504f.png)
I guess this is gtk-related since the menu icons are also tiny. Will #152 (port to gtk3) correct this?

Thanks!

**Comment by Osndok** [comment]
It has more to do with the fact that they are bitmapped/rasterized images. One project I know (LibreCAD) switched there interface images to SVGs, for this cause.

Relatedly, I notice that the images are:
1. not displayed in there native (pixel-for-pixel) size,
2. the 'X' seems to extend beyond the box (up/right), and
3. the right-arrow is very.... non-obvious.

Jaap, do you want me to open any of the above as separate issues?

For the last one, I came up with this:
![migrated-box](https://user-images.githubusercontent.com/80066/29131759-7c7152e8-7cf3-11e7-8528-d1d2b193ce25.png)

**Comment by jaap-karssenberg** [comment]
Yes this has to do with the default size for icons, actually you can change it through zim's "style.conf" config file. See the manual for hints to do that. The property to look for is "`bullet_icon_size`".

It does not have to do with PNG vs SVG, images will scale to large size if asked to do so.

**Comment by jaap-karssenberg** [comment]
@Osndok I'm open to improve the "[>]" icon, but the diagonal line doesn't work for me for "moved" tasks -- maybe we should follow up in a separate ticket

**Comment by nelas** [comment]
Ah, great! Setting `bullet_icon_size=ICON_SIZE_LARGE_TOOLBAR` did the trick.

Thanks!
