### ISSUE TITLE
Nextcloud-App for Zim

### ISSUE THREAD

**Issue by mahibi** [jaap-karssenberg/zim-desktop-wiki#185]
I use Nextcloud (www.nextcloud.com) to sync my Notes made with Zim Wiki between multiple computers (works great!).
It would be cool to have a WYSIWYG-Editor as a Nextcloud App for Zim Wiki Notes. 
(Altough there is no Zim-Wiki Android App, having a Zim-Wiki Nextcloud App would at least allow to view and edit the Notes via mobile webbrowser when connected to internet).

Are there any efforts to that?
I posted this idea also at https://help.nextcloud.com/t/make-an-app-for-zim-wiki/19867

**Comment by maxmv** [comment]
It's good idea. Nextcloud is very secure and flexible for collaboration.

**Comment by sunjam** [comment]
I strongly want this!  Best I've found currently is to view the Zim directories from within Nextcloud... all file links and media will be broken, but you can at least view the unformatted raw text files.

**Comment by jaap-karssenberg** [comment]
Closing as "won't fix" unless someone wants to pick it up and actively develop this
