### ISSUE TITLE
Move wiki to here

### ISSUE THREAD

**Issue by gutierri** [jaap-karssenberg/zim-desktop-wiki#187]
It seems to be interesting to move the [WIKI](https://github.com/jaap-karssenberg/zim-wiki/wiki) here, so it is simpler to find information and improve the organization.

**Comment by jaap-karssenberg** [comment]
Not yet decided what I wan't to do with the wiki - not moving it here untill I made up my mind about that

**Comment by jaap-karssenberg** [comment]
Closing for now - will deal with project structure in due time
