### ISSUE TITLE
Make Format:Bullet List work on current line if nothing is selected

### ISSUE THREAD

**Issue by ipsod** [jaap-karssenberg/zim-desktop-wiki#191]
Pretty often I'm converting a checkbox to a bullet or vice-versa.  It'd be nice if I could just use `Alt-m t` to change a checkbox to a bullet, add a bullet to the beginning of the line if there is none, or remove the bullet if there is one.

Also, the same applies to Format:Checkbox and Format:Numbered.

**Comment by mhinsch** [comment]
+1 That would indeed be extremely handy.

**Comment by jaap-karssenberg** [comment]
Duplicate of issue #154
