### ISSUE TITLE
can't run zim in mac getting "Can not import 'xdg.Mime' "

### ISSUE THREAD

**Issue by MoHD20** [jaap-karssenberg/zim-desktop-wiki#199]
I tired running zim in my Mac Sierra 10.12.3 but I get this error `WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'
`

**Comment by jaap-karssenberg** [comment]
This _warning_ should not prevent you from running zim, so if you can't run it, there must be something else going wrong.

**Comment by jansenfuller** [comment]
I ended up having this problem too.

This is what I did that fixed it.

1. Install prerequisites from Install page of the [zim website](http://zim-wiki.org/)

     - `brew install gtk-mac-integration`
     - `/usr/local/bin/pip install pyxdg`

3. Install and link Python 2.7.14 from Homebrew. 
4. With the new repo I ran
`/usr/local/Cellar/python/2.7.14_3/bin/python2.7 setup.py build`
`/usr/local/Cellar/python/2.7.14_3/bin/python2.7 zim.py`

After that, it ran perfectly. I hope this helps!

**Comment by kaxing** [comment]
Thank you @jansenfuller this works for me.
And in step 3: `$ python2 zim.py` would work fine;
In case symbolic links doesn't created correctly: `$ brew unlink python && brew link python`
And check again: ``` $ ls -l `which python2` ```

**Comment by lasombra** [comment]
I'm seeing this now with the master branch with Python 3.

```
~/Development/Personal/zim-desktop-wiki (master ✔) ᐅ python3.7 setup.py build           
Can not import 'xdg.Mime' - falling back to 'mimetypes'
Can not import 'xdg.Mime' - falling back to 'mimetypes'
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from zim import __version__, __url__
  File "/Users/iweiss/Development/Personal/zim-desktop-wiki/zim/__init__.py", line 195, in <module>
    import zim.config
  File "/Users/iweiss/Development/Personal/zim-desktop-wiki/zim/config/__init__.py", line 10, in <module>
    from .dicts import *
  File "/Users/iweiss/Development/Personal/zim-desktop-wiki/zim/config/dicts.py", line 35, in <module>
    from zim.utils import OrderedDict
ImportError: bad magic number in 'zim.utils': b'\x03\xf3\r\n'
```

**Comment by jaap-karssenberg** [comment]
@lasombra the warning about "xdg.Mime" is not the reason of the failure - it is just a message before the acutal failure.

In your case the failure is probably because python3 is trying to access files used by python2. Running "make clean" or just removing all "*.pyc" files in the tree should help. Or just delete the source and do a fresh checkout before running python3.

**Comment by jaap-karssenberg** [comment]
Closing as this is not an error - or not the real error at least
