### ISSUE TITLE
Certain pages are skipped when going to next/previous page in index

### ISSUE THREAD

**Issue by Self-Perfection** [jaap-karssenberg/zim-desktop-wiki#200]
Performing "Go / Next in index" on a page, starting with lowercase letter skips all pages, starting with uppercase letter.
Performing "Go / Previous in index" on a page, starting with uppercase letter skips all pages, starting with lowercase letter.

Confusing? Ok let's consider example notebook:
```
Home
├── AAA
├── BBB
├── ccc
├── ddd
├── EEE
├── FFF
├── ggg
├── hhh
├── III
├── JJJ
└── klm
```
Going to next page from `ddd` ends up on `ggg`. `EEE` and `FFF` were skipped!
And on the way back, going to previous page from `EEE` skips `ccc` and `ddd` directly to `BBB`

Observed on 0.67 and master but not on 0.65

Example notebook to test on: [Skipping pages.zip](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/1275400/Skipping.pages.zip)

**Comment by jaap-karssenberg** [comment]
Have observed the same issue myself, needs testing to pinpoint where it goes wrong
