### ISSUE TITLE
BUG full screen mode

### ISSUE THREAD

**Issue by maxmv** [jaap-karssenberg/zim-desktop-wiki#204]
Ubuntu 17.10 Gnome
After activate Gnome plugin Hide Top Bar https://extensions.gnome.org/extension/545/hide-top-bar/ can't disable Full screen mode in ZIM. It`s ZIM bug because other apps works as usual.

**Comment by jaap-karssenberg** [comment]
Can you elaborate a bit more on how it should work and what is happening instead ?

**Comment by maxmv** [comment]
Close it, please. All working good on clean Ubuntu installation.
Thanks!

**Comment by Osndok** [comment]
@maxmv Since you opened the issue, why are you putting closing the issue off on jaap? You should be able to close it from the github interface, and would be helping (however small) by saving him from just a wee bit of administration overhead.

**Comment by maxmv** [comment]
@Osndok Because I had not see button to close. Only after your comment I found this button.
