### ISSUE TITLE
Undo/Redo: Jump to position

### ISSUE THREAD

**Issue by msiism** [jaap-karssenberg/zim-desktop-wiki#205]
When performing an undo or redo action, Zim currently (0.67) doesn't jump to the position where that action is taking place inside the editor window. But it should, regardless of the current cursor position, to avoid confusion and potential data loss. Also, undeleted text should best be highlighted (like when selected with the mouse or keyboard). That is, btw, how LibreOffice behaves.

**Comment by sojusnik** [comment]
Is related to: https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/92
