### ISSUE TITLE
[macOS] Command-z doesn't work anymore in 0.66

### ISSUE THREAD

**Issue by brechtm** [jaap-karssenberg/zim-desktop-wiki#21]

**Comment by jaap-karssenberg** [comment]
No idea what can have changed there - menu binding is <Primary>Z as it was in previous release, mapping of <Primary> should be platform dependent, believe this is <Command> on OS X

**Comment by jaap-karssenberg** [comment]
Have you checked for error messages ?  Maybe mapping is OK, but the operation fails half way through.

**Comment by brechtm** [comment]
Ah. This is linked to the native OS X menu bar. If the OS X menu bar code is uncommented, some shortcuts do not work.
