### ISSUE TITLE
Shortcut for Insert Codeblock

### ISSUE THREAD

**Issue by lowk3y** [jaap-karssenberg/zim-desktop-wiki#211]
It would be nice if you could add keyboard shortcut for inserting Codeblock, it would eventually speed up writing things.

**Comment by Kiwon** [comment]
I also hope so

**Comment by Self-Perfection** [comment]
You can define your own keybindings for any menu item if you like. Please check "Changing accelerators" in "[Key Bindings](http://zim-wiki.org/manual/Help/Key_Bindings.html)" manual page.

**Comment by lowk3y** [comment]
hmmm .. can you be more specific how to do that? I see "Key Bindings" manual, but I don't see how to add new key binding to it; what to edit, how to do that .. thank you

**Comment by Self-Perfection** [comment]
Quote from that page

> Changing accelerators
> 
> Gtk+ implements a feature that allows you to change accelerators (keybindings for menu items) interactively. To use this feature you need to either enable this setting in the settings manager of you desktop environment or add the line:
> 
> gtk-can-change-accels = 1
> 
> to ~/.gtkrc-2.0 . Zim will remember any changes. If you ever want to reset to the default bindings just remove the "accelmap" file from ~/.config/zim/.

It was enough for me to google missing bits and set shortcuts that I need. Would you care to make pull request with clarification for this manual section?

**Comment by lowk3y** [comment]
@Self-Perfection I can read this but when editing "accelmap" what to insert there, I cannot find binding for Insert code block

`(gtk_accel_path "<Actions>/?????/????" "<Alt>b")`

**Comment by Self-Perfection** [comment]
The easiest way is to enable `gtk-can-change-accels`. If that is enabled it is enough to hover mouse cursor over menu item that needs changing and press desired hotkey

For manual editing you need to set accel for `"<Actions>/MainWindowExtension/insert_sourceview"`

**Comment by leafcutterant** [comment]
How can this be achieved on Windows?

**Comment by tai271828** [comment]
The approach of `Changing accelerators` seems unsupported. See:
- this commit of zim d628345b0f4a8eb43990bba8b1b1d33eeb370c8e
- [gtk-can-change-accels deprecated: 3.10](https://docs.gtk.org/gtk3/property.Settings.gtk-can-change-accels.html)

Workarounds/alternative solutions like [this](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/157#issuecomment-1193174629) may help.

**Comment by tai271828** [comment]
I found `Preferences` --> `Key bindings` has `<Actions>/inserted_objects/insert_code` for shortcut setting. For me I make it "Ctrl+I" and it works well (my zim source is the latest 2de3ea6350c81728c6ae88c22d57bcc0818a10f6 ) .

![Selection_289](https://user-images.githubusercontent.com/3217432/215359447-672cbb7e-81a9-4286-bd09-fb3d4a8ca61f.png)
