### ISSUE TITLE
Feature Request: Autocomplete for interwiki links

### ISSUE THREAD

**Issue by PrivateMandella** [jaap-karssenberg/zim-desktop-wiki#213]
I absolutely love Zim. It's easy to use and exactly what I wanted. However, it would be nice if the interwiki linking had an autocomplete feature. It is a really useful feature when linking within the notebook, and would be equally as useful when linking to another page in another notebook. Thanks!

**Comment by jaap-karssenberg** [comment]
Duplicate of #158
