### ISSUE TITLE
Renaming item with different capitalization creates duplicate in index

### ISSUE THREAD

**Issue by cr-mocz** [jaap-karssenberg/zim-desktop-wiki#215]
When an item exists in the index and it is renamed with different capitalization, it will appear in the index with both the old name and the new name.  Both items in the index will open the page, since the case-insensitive file name is the same.

Update Index and quitting/re-opening Zim makes no difference.  A few ways to fix it seem to be: 1) remove the txt file from the notebook folder, 2) Update Index, 3) put it back, 4) Update Index.
Or alternately: 1) move the txt to a different area of the notebook, 2) Update Index, 3) move it back

Example: create a page or sub page named "Zim" then rename it to "zim"

Occurs with Zim versions 0.65 through 0.67 using Windows 7 Home Premium SP1 (64-bit)

**Comment by cr-mocz** [comment]
Here is the relevant section of the debug log:

DEBUG: Action: rename_page
DEBUG: Opening dialog "Rename Page - Zim"
DEBUG: Dialog response OK
DEBUG: Opening ProgressDialog: Updating Links
DEBUG: Rename fitness to "Fitness" (False, False)
DEBUG: Move page fitness to Fitness
INFO: Rename C:\Zim\fitness.txt to C:\Zim\Fitness.txt
DEBUG: File exists "C:\Zim\fitness.txt" trying increment
**DEBUG: Index file: C:\Zim\fitness.txt
DEBUG: Index file: C:\Zim\Fitness.txt**
DEBUG: Closed dialog "Rename Page"
DEBUG: Action: close (delete-event)
DEBUG: Wrote C:\Users\Chris\AppData\Roaming\zim\cache\zim\notebook-C_Zim\state.conf
WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\__init__.py:1908: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed

WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\plugins\__init__.py:783: GtkWarning: gtk_ui_manager_remove_action_group: assertion `g_list_find (self->private_data->action_groups, action_group) != NULL' failed

**Comment by jaap-karssenberg** [comment]
3 items to fix:

1. In index.page_moved check files for equality and if equal purge the old one
2. In index.update_folder ensure that duplicates are detected as well (e.g. change happened outside of zim)
3. Bonus: for move that results in page name collapse ("Test page" --> "Test_page") detect in notebook.move_page and fail with explicit message (instead of assertion error that is thrown now)
