### ISSUE TITLE
Double-Click to Select Word - request

### ISSUE THREAD

**Issue by ComputerCarl** [jaap-karssenberg/zim-desktop-wiki#217]
Could you please implement the ability to double-click a word to select the word? It is a nice time-saver for formatting and changing.
Secondly - thank you for this very helpful software!

**Comment by Osndok** [comment]
Works for me! What is your platform/distribution, etc?

**Comment by ComputerCarl** [comment]
I am using Windows 7 x64
I was just reading #29 issue with copying and pasting and double-clicking which affects v0.66. I am using v0.66 after downgrading from v0.67 due to crashing intervals of less than an hour of use.. I am now going to downgrade to v0.65; apparantly that version was pretty stable.
