### ISSUE TITLE
Update Install instructions for Windows + win64 build?

### ISSUE THREAD

**Issue by lrq3000** [jaap-karssenberg/zim-desktop-wiki#220]
The instructions to install the requirements for Windows to run Zim from source is overly complicated, and in addition the PyGTK website now redirects to GTK3 instructions instead of GTK2 which is the one needed for Zim.

A much easier installation instructions can be found in .\windows\README-BUILD-win32.txt :

> 3. Install PyGTK All-in-One from
> 
> http://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/pygtk-all-in-one-2.24.2.win32-py2.7.msi
> 
> Be sure to include "PyGTKSourceView" and "PyRsvg" when you run the installer.

This is all that is needed to run from sources (PyGTKSourceView and PyRsvg are not even needed to just run, only to build).

However, these instructions only work for 32-bits win32 (32-bits Python, works even if you are on a 64-bits Windows, only the Python interpreter matters).

For Win64 (when you run a Python 64-bits install), then it's a lot more complicated. I first tried the instructions on PyGTK website and got this error:

```
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from zim import __version__, __url__
  File "C:\git\zim-desktop-wiki-joukhaha-fixed\zim-desktop-wiki-master\zim\__ini
t__.py", line 184, in <module>
    import zim.environ # initializes environment parameters
  File "C:\git\zim-desktop-wiki-joukhaha-fixed\zim-desktop-wiki-master\zim\envir
on.py", line 16, in <module>
    from zim.fs import ENCODING, isdir
  File "C:\git\zim-desktop-wiki-joukhaha-fixed\zim-desktop-wiki-master\zim\fs.py
", line 130, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "C:\git\zim-desktop-wiki-joukhaha-fixed\zim-desktop-wiki-master\zim\signa
ls.py", line 8, in <module>
    import gobject
  File "C:\Anaconda2\lib\site-packages\gtk-2.0\gobject\__init__.py", line 26, in
 <module>
    from glib import spawn_async, idle_add, timeout_add, timeout_add_seconds, \
  File "C:\Anaconda2\lib\site-packages\gtk-2.0\glib\__init__.py", line 22, in <m
odule>
    from glib._glib import *
ImportError: DLL load failed: %1 is not a valid Win32 application
```

Which is in fact because PyGTK does not provide Win64 binaries anymore, even though they did in the past!

I have found the following resources helpful to install Win64 binaries of the various libraries (there is no "all-in-one" installer unfortunately):
* https://stackoverflow.com/questions/14567921/python-pygtk-windows-7-64-bit
* https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/releases/tag/v1.0-win64

I can meet the requirements with these but then I get the following error:

```
> python zim.py --debug

** (python.exe:3140): WARNING **: Trying to register gtype 'GMountMountFlags' as
 enum when in fact it is of type 'GFlags'

** (python.exe:3140): WARNING **: Trying to register gtype 'GDriveStartFlags' as
 enum when in fact it is of type 'GFlags'

** (python.exe:3140): WARNING **: Trying to register gtype 'GSocketMsgFlags' as
enum when in fact it is of type 'GFlags'
INFO: This is zim 0.67-merge
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=12, releaselev
el='final', serial=0)
DEBUG: Platform is nt
DEBUG: No bzr version-info found
DEBUG: Running from a source dir: C:\git\zim-desktop-wiki-joukhaha-fixed\zim-des
ktop-wiki-master
DEBUG: Set XDG_DATA_HOME to C:\Users\AI\AppData\Roaming\zim\data
DEBUG: Set XDG_DATA_DIRS to [<Dir: C:\Users\AI\.local\share>]
DEBUG: Set XDG_CONFIG_HOME to C:\Users\AI\AppData\Roaming\zim\config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: C:\Users\AI\.config>]
DEBUG: Set XDG_CACHE_HOME to C:\Users\AI\AppData\Roaming\zim\cache
DEBUG: Connecting to \\.\pipe\zim-AI-0.67-merge-e38a921a-primary
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Registered object line
***CRASH***
```
I added the ```***CRASH***``` at the end because the application just crashes, no window gets displayed.

This is not high priority, I just wanted to leave here what I tried in case it can save someone else's time.

I can also try your suggestions on my machine if you have any, feel free!

**Comment by jaap-karssenberg** [comment]
Closing as we are porting zim to Gtk3 -- work in progress
