### ISSUE TITLE
Save latex code in documents

### ISSUE THREAD

**Issue by Boruch-Baum** [jaap-karssenberg/zim-desktop-wiki#221]
Unless I'm missing something, the equation editor plugin inserts an image into the zim document and loses the latex code used to create the image. It would be real useful to store that, so a user can modify it in some future session instead of having to start again from scratch. This would be especially useful for complex latex code and for people who don't use latex much.

Of course, nothing (except human nature) is stopping a user from remembering to manually copy and paste the latex code into the zim document before pressing the 'OK' button.

Great program!

**Comment by Osndok** [comment]
I think that is only half-true, have you tried right-clicking on the resultant image? I think you should find an 'edit equation' option.

**Comment by jaap-karssenberg** [comment]
I think you are indeed missing something, the latex is saved as a .tex file next to the image and indeed as @Osndok commented you can re-edit the equation.

**Comment by Boruch-Baum** [comment]
@Osndok : Thanks. I hadn't tried that.

@jaap-karssenberg : I don't see any .tex data next to the image (zim version 0.65-4, in debian), but as @Osndok mentioned, right clicking returns me to the editor
