### ISSUE TITLE
Tasklist: bring back filter by label for checkbox lists

### ISSUE THREAD

**Issue by fmos** [jaap-karssenberg/zim-desktop-wiki#222]
(This is essentially a copy of https://bugs.launchpad.net/zim/+bug/1708379)

The Task List plugin provides a configuration to "Consider all checkboxes as tasks" (checkbox) and a setting for "Labels marking tasks" (text field), which defaults to "FIXME, TODO".

Expected behaviour and actual behaviour until version 0.65 is that when the checkbox is unchecked, **only** tasks preceeded by one of the labels (either on the same line or on the line above) are included in the task list. 

Since version 0.66 and also in present version 0.67 this filter does not work any longer. Irrespective of the checkbox setting, all checkboxes in the entire notebook are considered as tasks and displayed in the task list. (The option for enabling the expected functionality is marked as "TODO" in the source code; hence this is basically a known regression.)

In my case, the notebook has more than 5000 checkboxes, but (hopefully) only a fraction of those are tasks. I can work around the bug by appending an additional @ label to all actual tasks. The problem is that apparently all checkboxes seem to be indexed for the task list: if the task list is displayed, Zim freezes for about 5 seconds every time I save a page and on autosave, significantly degrading the user experience. Thus I'm forced to keep the task list closed at all times, which is hardly the point of a task list ...

The problem can be reproduced with a new notebook with the following Home.txt. When opening the task list, two items ("No task" and "task") are listed, irrespective of the state of the "Consider all checkboxes as tasks" checkbox in the Task List settings.

```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4
Creation-Date: 2017-08-03T09:25:22+02:00

====== Home ======
Created Donnerstag 03 August 2017

[ ] No task

TODO:
[ ] task
```

**Comment by fmos** [comment]
A fix is proposed in fmos@c84a9ff 
Before I open a pull request, I'll also adapt the test case.

**Comment by jaap-karssenberg** [comment]
@fmos proposed fix looks good - give me a heads up when ready to merge

The known regression is a **** up on my side, should not have merged with that TODO still in

**Comment by fmos** [comment]
@jaap-karssenberg Thanks for the review and feedback! Ready to merge now - in case there were any doubts.
