### ISSUE TITLE
code said I found a bug.

### ISSUE THREAD

**Issue by dtd41** [jaap-karssenberg/zim-desktop-wiki#234]
Error text is below. I deleted a node with some sub-nodes getting a pop-up box and an error message. To attempt to get rid of the error I logged out of xfce and deleted /home/doug/Notebooks/Notes/.zim/index.db and status.conf in the same dir. When I logged back in the node (and error) were still present in the side-panel but the pages have been deleted. So I repeated the deletes and rebooted. The error is now gone but the node is still present with no pages. After the reboot most of the data relative to the node is not in index.db.

artemis:~/Notebooks/Notes/.zim> strings index.db | grep waldo
waldo77616c646f 8

Going into zim all three levels of the node waldo are present with empty pages.

The error reported:
-----------------------------------
This is zim 0.65
Platform: posix
Locale: None None
FS encoding: utf-8
Python: (2, 7, 13, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
Zim revision is:
  branch: zim-trunk
  revision: 805 jaap.karssenberg@gmail.com-20151101144245-0g7s8a7qjt5xu1d0
  date: 2015-11-01 15:42:45 +0100

======= Traceback =======
  File "/usr/local/lib/python2.7/site-packages/zim/gui/widgets.py", line 3106, in do_response
    destroy = self.do_response_ok()
  File "/usr/local/lib/python2.7/site-packages/zim/gui/__init__.py", line 3282, in do_response_ok
    lines = self.page.dump(format)
  File "/usr/local/lib/python2.7/site-packages/zim/notebook.py", line 2507, in dump
    tree = self.get_parsetree()
  File "/usr/local/lib/python2.7/site-packages/zim/notebook.py", line 2409, in get_parsetree
    assert self.valid, 'BUG: page object became invalid'
AssertionError: BUG: page object became invalid

So I typed into each of the three pages. index.db had no more references to waldo but a state.conf was created:

artemis:~/Notebooks/Notes/.zim> cat state.conf 
[History]
list=[["Home",19,null],["Safeport:waldo:mysql",20,null],["Safeport:waldo:mysql:its4Dfries:never",20,null],["Safeport:waldo",20,null],["Safeport:waldo:mysql",0,null],["Safeport:waldo:mysql:its4Dfries:never",32,null],["Safeport:waldo:mysql:its4Dfries",31,null],["Safeport:waldo:mysql",19,null],["Safeport:waldo",32,null]]
recent=[["Home",19,null],["Safeport:waldo:mysql:its4Dfries:never",32,null],["Safeport:waldo:mysql:its4Dfries",31,null],["Safeport:waldo:mysql",19,null],["Safeport:waldo",32,null]]
current=8

[MainWindow]
windowpos=(0, 0)
windowsize=(600, 450)
windowmaximized=False
active_tabs=null
show_menubar=True
show_menubar_fullscreen=True
show_toolbar=True
show_toolbar_fullscreen=False
show_statusbar=True
show_statusbar_fullscreen=False
pathbar_type=recent
pathbar_type_fullscreen=none
toggle_panes=[]
left_pane=[true,200,"Index"]
right_pane=[false,200,null]
top_pane=[false,200,null]
bottom_pane=[false,200,null]
readonly=False

**Comment by jaap-karssenberg** [comment]
Closing this report because I believe this issue to be gone in the 0.67 release
