### ISSUE TITLE
symlink to notebook is destroyed with Zim 0.67

### ISSUE THREAD

**Issue by rzwisler** [jaap-karssenberg/zim-desktop-wiki#238]
I have my actual Notebook directory located outsize of ~/Notebooks, and I access it via a symlink.

i.e.:  
~/Notebooks/Work -> ~/.somedirectory/Work

I do this so my 'Work' directory can be part of a larger git repo.

This works fine in Zim 0.65, but when I upgrade to Zim 0.67 the link is occasionally wiped out while Zim is running, and a new empty ~/Notebooks/Work directory is created.  This normally happens to me when moving pages between directories in my notebook.

**Comment by raincomplex** [comment]
I am also experiencing this. It seems to trigger when you rename top level pages but not subpages. Replication steps:
* mkdir test; ln -s test sym; zim ./sym
* save the "Home" page
* create a new top level page called "one" and save it
* rename "one" to "two"
* the rename will have worked in 'test', but the symlink will be gone, and zim starts a new empty notebook at that path (if you save anything)

**Comment by raincomplex** [comment]
This probably isn't the best solution -- I wonder if it's better to just never delete symlinks, since zim never makes them. Is there a case where a symlink definitely should be deleted?
