### ISSUE TITLE
cannot hide big "Index" bar on left side of screen

### ISSUE THREAD

**Issue by rzwisler** [jaap-karssenberg/zim-desktop-wiki#239]
Even when the side pane is minimized, with version 0.66 and beyond there is a big blank space on the left side of the notebook with just an "Index" button on it.  This wasn't there in version 0.65.

Can you please add an option to the "View" menu or something so I can get rid of it and maximize my typing/reading space?

**Comment by jaap-karssenberg** [comment]
I did this on purpose as I don't see a good alternative to make panes "discoverable".

Will close as "won't fix" for now, but I'll take your feedback along in the Gtk3 redesign
