### ISSUE TITLE
headers (Tag h1, Tag h2, etc) don't respect "font" property

### ISSUE THREAD

**Issue by rzwisler** [jaap-karssenberg/zim-desktop-wiki#240]
As described here:

http://zim-wiki.org/manual/Help/Config_Files.html

style tags often have a "font" property where you can specify both a font and a size.  It doesn't look like the header tags ("Tag h1", "Tag h2", etc) respect these font properties.  This means that for recent versions of Zim (0.66 and 0.67) the headers are all different sizes, and that this cannot be changed.

With version 0.65 all the headers were the same size, which is what I prefer and would like to get back to.

**Comment by jaap-karssenberg** [comment]
I think looking at the default config file is instructive: https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/master/data/style.conf 

You can easily see that each header has a different "scale" property.
