### ISSUE TITLE
versioncontrol: zim is too aggressive in updating the git index

### ISSUE THREAD

**Issue by raincomplex** [jaap-karssenberg/zim-desktop-wiki#249]
If a zim notebook is part of a larger git repo, it can be a hassle to have zim updating the index while you are working on things for a commit. I think it would be better if instead of updating it when pages are changed, it simply did a `git add $NOTEBOOK_ROOT` before committing with the "save a version" menu item. This has the following benefits:
* the user has full control over the git index in larger repos
* you don't need to use `-a` when committing (because of the `git add`), which will avoid capturing unrelated repo changes in a zim commit
* there is no change to the workflow for someone whose repo only contains a zim notebook

**Comment by Osndok** [comment]
Actually, I think that you *do* need the '-a' to pick up on deleted and moved files.

**Comment by raincomplex** [comment]
Nope. `git add` on the notebook root will detect those.

I'm working on a patch for this.
