### ISSUE TITLE
Tray icon click behaviour, zim 0.66

### ISSUE THREAD

**Issue by guilhas** [jaap-karssenberg/zim-desktop-wiki#25]
Hello,

Would it be possible to revert the click tray icon behaviour?

- 0.65
  - Open Zim wiki main window

- 0.66
  - Open a small window with one clickable option, and then open main window
   ![image](https://cloud.githubusercontent.com/assets/456810/25870911/afe760ce-34fd-11e7-9eb4-877b5b0fc78c.png)

OS: win7

Best App ever

Regards,
Lino

**Comment by jaap-karssenberg** [comment]
From my testing:
- left click has a bug - fixed available, after fix pop the default notebook
- right click shows menu - as expected

Don't observer the change in behavior from 0.65 to 0.66 you mention. Maybe you are using different mouse button because of the bug ?

Regards,

Jaap

**Comment by guilhas** [comment]
Hello,

0.67 Latest
* LBM click opens the small menu shown above.
* RBM shows the standard menu with Quit option

In 0.65
* LBM click directly open notebook

Regards,
Lino

**Comment by guilhas** [comment]
I think I will start using a windows shortcut (Zim.lnk) with Ctrl - Alt - Z to open main window.
And remove clicking in tray from my workflow
