### ISSUE TITLE
Pasting text from wiki causes error in last line indent formatting.

### ISSUE THREAD

**Issue by David-Bear** [jaap-karssenberg/zim-desktop-wiki#252]
Copying a block of indented text from the wiki and pasting it elsewhere in the wiki causes the final line of the text block to be formatted incorrectly. This error appears as if the line were moved left by three spaces. Shift-tabbing to the the beginning of the newline, and tabbing to the correct position fixes the format issue.

**Comment by jaap-karssenberg** [comment]
Closing for now. Please re-open if you have the information on how to reproduce
