### ISSUE TITLE
Segmentation fault when scrolling pages pannel

### ISSUE THREAD

**Issue by cocconat** [jaap-karssenberg/zim-desktop-wiki#256]
I m using Arch Linux, just after last update I m experiencing this problem, I ve already update newly.
When opening (scrolling with keyboard arrows is safe) with click or enter one of pages in left panel it closes all of a sudden. Opening by terminal I got 

> WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'
> WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'
> WARNING: Could not find all icon sizes for the application icon
>   5569 segmentation fault (core dumped)  zim --standalone

without standalone

> 6055 segmentation fault (core dumped)  zim

Anyway I can digit in a new page, I cannot browse!

pls help!!!

**Comment by Osndok** [comment]
I don't think that one can (in theory) cause a segmentation fault in pure python, so this is **probably not a zim problem**.

I recommend that you attach gdb to the process and capture a backtrace, it should help narrow down the offending software.

**Comment by cocconat** [comment]
Hi, it runs into error for missing dictionaries, I ve understood that with Valgrind eheheh
Sorry for the useless Issue, anyway I suggest you to add a ValueError or something like in this case :) thanks for the amazing program
