### ISSUE TITLE
Custom tools: commands can't include pipe (|) character

### ISSUE THREAD

**Issue by rodom** [jaap-karssenberg/zim-desktop-wiki#259]
I've tried creating a custom tool to sort a list in a page, with command `echo "%t" | sort`. I created it with "Output should replace current selection" checked; if I select the text...
```
c
b
a
```
...and run the tool, I just get...
```
c
b
a
 | sort -n
```
Obviously I'd expect...
```
a
b
c
```
...but it looks like the `|` is being escaped and passed as an argument to `echo` instead of being left for the shell to interpret.

**Comment by Self-Perfection** [comment]
As far as I can tell from browsing sources custom runs here
https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/7a373a788194c36723bd0eed600291e513de9396/zim/gui/applications.py#L1172-L1174
which essentially executes
https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/7a373a788194c36723bd0eed600291e513de9396/zim/applications.py#L188-L195
Thus it is not escaping that makes things go the other way that you expect but the fact a shell is not used at all to launch command. And IMHO it's a feature: shell wrapper for running commands is a considerable overhead.

To get desired result you should run command via shell manually:
`sh -c 'echo "$0" | sort' "%t"`
also consider replacing `%t` with `%T` to preserve wiki formatting.

Finally: not a bug IMHO

**Comment by jaap-karssenberg** [comment]
Indeed not a bug - the custom command runs an executable, not a shell
command.

To run a shell command, you can create a ".sh" script file and run that
script as a custom tool.

Regards,

Jaap

**Comment by rodom** [comment]
Thanks both, that makes sense, and @Self-Perfection that works for me. Might be worth documenting that approach somewhere, it's very useful.
