### ISSUE TITLE
Mac OSX App

### ISSUE THREAD

**Issue by izhakjakov** [jaap-karssenberg/zim-desktop-wiki#262]
Hi All

I would like to share a simple mac osx app for Zim that I created
It is basically 3 files: ($> find  /Applications/Zim.app/ -type f)

```
/Applications/Zim.app/Contents/MacOS/Zim           # sh script
/Applications/Zim.app/Contents/Resources/zim.icns  # icon
/Applications/Zim.app/Contents/Info.plist          # property list (app configurations)
```
[Zim.zip](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/1568387/Zim.zip)

**Comment by staeff** [comment]
Thats handy. Thanks!

**Comment by takacsot** [comment]
Great. I love it.

I did some custom app basedon various articles and none of them handled certain things effectively (typically zim was instable and keybaord shortcuts were non Mac-like - I have to use CTR+v instead of CMD+v - frustrating :) ).

But this version seems to be working perfectly with Mc shortcuts and now collapsing :)

I really recommend to publish on main website

**Comment by luhengtong** [comment]
Sir, I have some trouble when l use the app for Zim. It has a flashback.
When I run the sh script. It gives me this information:

/Applications/Zim.app/Contents/MacOS/Zim ; exit;
/Applications/Zim.app/Contents/MacOS/Zim: line 6: /usr/local/bin/zim: No such file or directory
/Applications/Zim.app/Contents/MacOS/Zim: line 6: exec: /usr/local/bin/zim: cannot execute: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...58 completed.

I hope I can get some help. Thank you!

**Comment by izhakjakov** [comment]
Hi luhengtong

The app I shared here is not Zim but wrapper script to start Zim on mac
If you wish to use this app you should first install Zim then run the app
If you would like to be in your launcher drag the .app file into /Applications on the Finder's left pane

I could probably Zim's binary files into Zim.app but then you would have to replace the Zim.app every time there is a new update (unless the brew crew will include it in their repository)

Also you are still going to have to make sure you have the dependencies (e.g. python) to be able to run the app.

The easiest way I think is to use to install Zim using brew:
`brew install zim`
then drag the app to /Applications (In finder hold: ⌘ + ⇧ + G then type /Applications in the opened window)

BTW, if you did install Zim already modify the last line in Zim/Zim.app/Contents/MacOS/Zim:
`exec /usr/local/bin/zim;`
to whatever path you have zim on your computer.

Sorry I wrote so much hope this helps and not too confusing

Let me know how it goes or if you have any more questions / suggestions
Goodluck  :-)

**Comment by luhengtong** [comment]
Hi Izhak Jakov

Thank you for your replying! I understand what you say.
I used to install zim by brew. But something was wrong. I think it is not a problem with zim.
I can open zim, but I can't input Chinese. Maybe it is a problem with gtk or xdg.
It's too trouble. So I give up. I install virtualbox for ubuntu, and install zim on ubuntu.

Thank you for your help!

**Comment by izhakjakov** [comment]
Hi luhengtong

Another reason I created the app was an issue with the local in Zim
`export LANG=en_CA.UTF-8`
You can try installing Zim using brew again the use my app to open it:
Modify the value of LANG in Zim.app/Contents/MacOS/Zim to whatever you need, then run the app.

**Comment by jaap-karssenberg** [comment]
I think this is great information, but please put it on the user wiki here: https://github.com/jaap-karssenberg/zim-wiki/wiki

**Comment by izhakjakov** [comment]
Thank you Jaap
I have created a [new page](https://github.com/jaap-karssenberg/zim-wiki/wiki/Mac-OSX-App-(wrapper))

**Comment by brechtm** [comment]
Great! I didn't realize it was this simple to create a Zim "app".

However, I have two issues with it:
- for some reason, it will not start from Alfred
- it's not possible to exit Zim by using the "Quit" context menu item of the Zim icon in the dock
- macOS cannot automatically close Zim on restart/shutdown

I assume the latter two share the same cause.

**Comment by brechtm** [comment]
I've updated the macOS Menubar plugin (#1008), fixing these issues.
