### ISSUE TITLE
Nested tags

### ISSUE THREAD

**Issue by Nick222** [jaap-karssenberg/zim-desktop-wiki#263]
Can user create nested tags, for example:

@science|chemistry

Then in Tags window appear:
- science
-- chemistry

May be three levels will be enough...

**Comment by Osndok** [comment]
I think tag **arguments** would be more likely to happen than this; IMO your request would amount to re-implementing pagelinks, which already do "nesting".

Try either:
* :Tag:Science:Chemistry
* @science @chemistry

A tag is supposed to be much like a "hashtag" (for faster searching) not for general purpose organization & browsing.

**Comment by Nick222** [comment]
But tag @science and then (in search results) tag @chemistry - it can do search more fast.
It is logical link from science to chemistry.
Another way - I must create tags: @science_chemistry @school_chemistry @home_water_chemistry and so on.
I create big text`s collection (pages nested by date) and try to use tags to organize it...

In some programs I can use nested tags and tags with arguments...

**Comment by Osndok** [comment]
Actually... it would be faster to search for @chemistry if you are searching for chemistry :) , or (as I recommended) open the 'jump' dialog type :Science (which will auto-suggest all the 'tags' under :Science ), large file-set latency notwithstanding.

**Comment by Self-Perfection** [comment]
This conversation seems for me very much related to conversation in #236 @Nick222 take a look there

**Comment by jaap-karssenberg** [comment]
For me this is "won't fix" because the page hierarchy already offers a mechanism to organize / link content in a nested structure. You can combine multiple tags to create more specific search queries.
