### ISSUE TITLE
Link to "Workflow for issues"

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#265]
Would be great to have a link to "[Workflow for issues](https://github.com/jaap-karssenberg/zim-desktop-wiki/wiki/Issues)" in the "[issues](https://github.com/jaap-karssenberg/zim-desktop-wiki/issues)" section, like shown [here](https://i.imgur.com/o9WjXw6.png) and also when creating a new issue, like shown [here](https://i.imgur.com/v9pMkhk.png).

Mentioning those "guidelines" in the [readme.txt](https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/master/README.txt) would also help, imho.

**Comment by sojusnik** [comment]
Or something like [this](https://i.imgur.com/wo2N6zw.png).

**Comment by jaap-karssenberg** [comment]
Github supports showing such text via a "CONTRIBUTING" file. This is part of #143
