### ISSUE TITLE
Math preview replaces the latex code by a picture

### ISSUE THREAD

**Issue by lrq3000** [jaap-karssenberg/zim-desktop-wiki#270]
Currently, when using a Math preview, the latex code will be replaced by a picture, so it is impossible to go back to modify the equation (eg, to fix it, or to just copy/paste the latex code elsewhere such as in a latex document).

It would be very useful to just generate the picture on-the-fly, or to store it alongside the latex code (ie, the picture could be stored in the Zim Notes folder just like any other picture, and the latex code could be kept in the image stored in the alternative text/title text), or both (ie, keeping in the note only the latex code, but Zim Notes could check if the equation was already rendered as a picture and load the picture if available, else would render on-the-fly and store the picture - this could be done by generating a hash from the equation latex code and name the picture with this hash).

**Comment by Self-Perfection** [comment]
Hi @lrq3000 
Your latex code is not lost after image gerenation bit is stored alongside with image itself in `*.tex` file. And is accessible within zim itself: just right click equation image and choose "Edit Equation".

**Comment by lrq3000** [comment]
@Self-Perfection You're correct! Thank you very much! I don't know how I missed this feature, maybe it was not there in a previous release, but that's perfect now!
