### ISSUE TITLE
Pascal case links

### ISSUE THREAD

**Issue by banan314** [jaap-karssenberg/zim-desktop-wiki#274]
When I write text using PascalCase (upper camel case), it is automatically transformed into a link to a new page. The page is not created, but is visible and greyed out in the index. Isn't it confusing for the user? Also, I can't see anything about this feature in Help.
For example, type 
```
FaD
```
anywhere and the colour changes to blue. 

Pascal case words shouldn't be automatically transformed into links.

**Comment by Self-Perfection** [comment]
This behavior is managed by setting Preferences -> Editing -> Automatically turn "CamelCase" words into links. I checked manual and this feature is referenced or described in four different pages, just Ctrl-Shift-F "*Camel*" in manual notebook and you'll find them.

IMHO this issue does not describe a bug and is subject to be closed.

**Comment by banan314** [comment]
Strange, but I have to search for _CamelCase_ in the help to see pages. Search for _Camel_ doesn't give me any results. 

Closing the issue, because the behavior is managed in preferences.

**Comment by Self-Perfection** [comment]
@banan314 my bad. I intended to suggest you search for "`*Camel*`", but github ate asterisks as markdown formatting and made word "Camel" italics. By default Zim "Search..." command searches whole words, but supports pattern search using asterisk instead unknown word fragment.
