### ISSUE TITLE
Heading markdown in Templates and Page work opposite

### ISSUE THREAD

**Issue by petergruenbeck** [jaap-karssenberg/zim-desktop-wiki#276]
In the pages:
== is Heading 1
=== is Heading 2
etc. with no closing ==

while in the templates (Journal)
====== Heading 1 ======
===== Heading 2 ======
etc.

**Comment by Self-Perfection** [comment]
Why do you suppose this is a bug? Documentation [states](http://zim-wiki.org/manual/Help/Wiki_Syntax.html) that Zim syntax is a slightly modified [DokuWiki syntax](https://www.dokuwiki.org/wiki:syntax), and headers syntax in Zim and DokuWiki match. Zim do not claim that it can edit markdown documents.

**Comment by jaap-karssenberg** [comment]
Yes, this is not as nice and consistent as could be, but intended behavior and not a bug
