### ISSUE TITLE
Startup fails for non-admin user Win10, 64-bit, zim 0.66

### ISSUE THREAD

**Issue by GAJansen** [jaap-karssenberg/zim-desktop-wiki#28]
I tried to upgrade zim from v0.65 to v0.66.
I use a normal user account, and during installation had to confirm the admin password.
OS: Win10, 64-bit.
Installation of v0.66 (over an existing v0.65, using 'Zim-setup-0.66_2017-05-07.exe') seemed OK, no errors here.
When starting the newly installed v0.66 as normal user, the following is shown in an error window:

> This is zim 0.66
> Platform: nt
>Locale: nl_NL cp1252
>FS encoding: mbcs
>Python: (2, 7, 13, 'final', 0)
>Gtk: (2, 24, 0)
>Pygtk: (2, 24, 0)
> No bzr version-info found
> 
>======= Traceback =======
>   File "zim\main\__init__.pyo", line 745, in main
>   File "zim\main\__init__.pyo", line 554, in run
>   File "zim\main\__init__.pyo", line 576, in _run_cmd
>   File "zim\main\__init__.pyo", line 597, in _run_main_loop
>   File "zim\main\ipc.pyo", line 127 in start_listening
> AssertionError: Listener did not start

Unfortunately, I was able to select and copy the text in the error window, but the 'pasting-option' was disabled (grayed-out) in both this window, MS-Notepad, and Notepad++, so I had to manually type the error message. Probably this window is 'admin-copy-protected'?

_When running zim 0.66 **as admin**, I experience no problems._

Reinstalling v0.65 (using 'Zim-setup-0.65_2016-01-18.exe') went smoothly, and now I am able to run zim as normal user again.

Apparently something goes wrong in the 0.66 installer on Win10, 64-bit version.

NB: 
- the upgrade on another machine running Win7 Starter, 32-bit, went well, and zim runs fine for a normal (no admin) user.
- the upgrade on yet another machine running Win10, 32-bit, also went well, and zim runs fine for a normal (no admin) user.

**Comment by jaap-karssenberg** [comment]
Not sure what is happening here - somehow you are not allowed to start a named pipe for communication (?)

Next version will fallback to "standalone" mode if this error is encountered. So even if we can't solve it, at least it won't be fatal.

**Comment by GAJansen** [comment]
I am not enough of an expert to understand the meaning of 'start a named pipe for communication', sorry about that.
However, the fact that the reinstall of v0.65 went OK and this version runs smoothly on my system seems to point out that the processes using this previous version do not encounter this 'named pipe communication error'. Again, I am not an expert here, but is the call for this pipe in v0.65 also used, and if so, is this any different from the one used in v0.66?
Just a thought, don't blame me for any ignorance...

Looking forward to a fix!

Cheers,
GAJansen

**Comment by jaap-karssenberg** [comment]
The previous version does roughly the same thing, using the same libraries. Details differ, but I can't understand either how that would make a difference on your system.

Only thing I can offer is the fallback mode mentioned above, at least that makes the error non-fatal.

**Comment by bkidwell** [comment]
@jaap-karssenberg please assign this to me. I will try to fix it within the next month or so.

**Comment by opuslux** [comment]
It's the wrong place to post this but at least it targets the same build: I tested various Win7 / Win10 / 64bit systems with portable and installer distributions of zim build 0.66. All of these combinations suffered from the "cannot copy from zim to another application (like notepad++, mail and so on)" - problem. 

In addition I recognize not being able to "double-click-2-select-words" in pages. Made me crazy - almost gave up on migrating from cherrytree to zim until I gladly testet version 0.65 - here almost everything works like a charm.

**Comment by jaap-karssenberg** [comment]
@bkidwell looks like I cannot assign (only myself and the person who opened the tickets) maybe you can do it yourself though. On the upper right-hand side under "Assignees" it reads "assign yourself" for me, if you have that as well you can assign yourself.

**Comment by bkidwell** [comment]
@jaap-karssenberg I am not a member of the project record in GitHub. Non-members can't edit the assignee field, and probably also can't be assigned to issues. Add me to the project.

**Comment by bkidwell** [comment]
This issue is probably fixed in my merge request against 0.67-rc2. I upgraded to NSIS 3. They say NSIS installers from pre-3.0 were failing to start on Windows 10 and this has been fixed in NSIS.

A build is available on https://zim.glump.net/ .

Will test later this week.

**Comment by GAJansen** [comment]
@jaap-karssenberg 
@bkidwell 

I can confirm that the installation of zim 0.67 on my Win10 64-bit machine went OK, and that I am able to run it as a normal user. Also, I am able to copy text form Zim notes into other applications.

Thanks for your efforts Jaap and Brendan!

N.B. This issue can be marked as fixed.

**Comment by jaap-karssenberg** [comment]
@GAJansen thansk for verifying !
