### ISSUE TITLE
How to use files from the repository?

### ISSUE THREAD

**Issue by it19862** [jaap-karssenberg/zim-desktop-wiki#280]
How to open a project in Visual Studio to make changes for yourself?

ps
I apologize if the question is simple, I'm just learning programming

**Comment by Osndok** [comment]
Is this, somehow, a zim-specific question? Are you asking how to directly edit zim pages ("Tools" menu -> "Edit Source")? or edit the source code?

**Comment by it19862** [comment]
@Osndok 
I mean add my buttons.
I want to make the keyboard shortcut "Ctrl + C" work.
As well as other improvements to perform independently

**Comment by jaap-karssenberg** [comment]
Afraid I can't help you with visual studio, but you can make changes with any editor. Probably you should start with instructions here on GitHub on checking out repositories and go from there,
