### ISSUE TITLE
How do I make the "Create page ..." menu "Create subpage ..." active?

### ISSUE THREAD

**Issue by it19862** [jaap-karssenberg/zim-desktop-wiki#281]
How do I make the "Create page ..." menu "Create subpage ..." active?
![3070](https://user-images.githubusercontent.com/18245828/34469546-7e8188c6-ef32-11e7-8cae-5dea267651f9.jpg)

**Comment by Osndok** [comment]
I think the only time that option is disabled is when the repository (or page?) is read-only; so I would check the mount point & file system permissions.
