### ISSUE TITLE
Fwd:  [abrt] Zim: update_completion(): widgets.py:2005:update_completion:AttributeError: 'NoneType' object has no attribute 'get_model'

### ISSUE THREAD

**Issue by cheese** [jaap-karssenberg/zim-desktop-wiki#283]
Version-Release number of selected component:
Zim-0.67-2.fc27

Additional info:
reporter:       libreport-2.9.3
cmdline:        /usr/bin/python /usr/bin/zim
crash_function: update_completion
exception_type: AttributeError
executable:     /usr/bin/zim
kernel:         4.14.8-300.fc27.x86_64
runlevel:       N 5
type:           Python

Truncated backtrace:
widgets.py:2005:update_completion:AttributeError: 'NoneType' object has no attribute 'get_model'

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zim/signals.py", line 414, in callback
    self.cb_func(*arg, **kwarg)
  File "/usr/lib/python2.7/site-packages/zim/gui/widgets.py", line 2005, in update_completion
    model = self.get_completion().get_model()
AttributeError: 'NoneType' object has no attribute 'get_model'

Local variables in innermost frame:
text: ''
self: <PageEntry object at 0x7f6ac2aa1960 (zim+gui+widgets+InputEntry at 0x558759b49a30)>

**Comment by jaap-karssenberg** [comment]
Do you have instructions how to reproduce this issue ?

**Comment by jaap-karssenberg** [comment]
Fixed in current master branch (if not, give  me few days to sync offline work)
