### ISSUE TITLE
Incorrect rendering of the @ symbol

### ISSUE THREAD

**Issue by xvusrmqj** [jaap-karssenberg/zim-desktop-wiki#285]
when i write "xxx@xxx". it become blue and a link. but this is not a email . it just a plain text . 

for example. 
`@Configuration和@EnableSwagger2后再加一个注解@Conditional(TestConfigCondition.class).`

if i add a blank space before @ symbol , it still blue link and click it then get a subpage.

**the @ symbol is the  `java keyword `not` email keyword` and not `a subpage keyword `.
 I donot want it be a blue link.**
  
  
==============update=================
it become  yellow text, not blue . but I want it black. 
what exactly the @ symbol means ? 

I use window lastest version.

**Comment by Self-Perfection** [comment]
Word starting with `@` [is a tag](http://zim-wiki.org/manual/Help/Tags.html).

**Comment by xvusrmqj** [comment]
How to disable tag? I do not need it .  
or How to make @ symbol not a auto tag.

**Comment by Self-Perfection** [comment]
Use verbatim formatting on that text. Verbatim formatting should be used on anything code-like to prevent parsing it parts as wiki syntax.

**Comment by xvusrmqj** [comment]
@Self-Perfection it works , thank you ! :+1:
