### ISSUE TITLE
Can somebody create script to import data from RedNotebook ?

### ISSUE THREAD

**Issue by Nick222** [jaap-karssenberg/zim-desktop-wiki#289]
Can somebody create script to import data from RedNotebook ?

It create per month files with name 2017-12.txt and content :

> 2: {text: 'Example
> 
> 
>     [Google ""http://google.com""]
> 
> 
>     ====================
> 
> 
>     Line break\\
> 
> 
>     ``Mono``
> 
> 
>     --Strikethrough--
> 
> 
>     [ReadMe.txt ""file:///home/ReadMe.txt""]
> 
> 
>     [""file:///home/Picture"".png]
> 
> '}
> 12: {text: "Example\\\\\nExample\n\nExample **Bold** //Italic// __Underline__\\\\\n\nExample
>     __//Example//__ __**Example**__ //**Example**// __//**Example**//__ Example\n\nNumber
>     list:\n+ Example\n + Example\n+ Example\n\n\nMark list:\n- Example\n - Example\n-
>     Example\n- Example\n\n\nTwo empty lines after list to return to normal paragraph\n"}

**Comment by ziggystar** [comment]
# Simple conversion using a bash script

## Export from Rednotebook
I used the text export of Rednotebook. It creates a single text file with only minor markup. Use `%y-%m-%d` as date format. I did not export the tags, don't know what happens. 

## Run through script

Then use below bash script with the rednote exported file as single argument. The files might require some manual formatting, but at least zim did not raise any errors for me when copied into the `Journal/` directory.

```
#!/bin/bash

# - remove trailing spaces from date
# - remove date underline
# - split into files at dates
sed -e "s/^  //" $1 \
    | sed -e "s/========//" \
    | csplit -z -f day - "/^[0-9]*-[0-9]*-[0-9]/" "{*}"

for f in day*; do
    IFS=-
    read y m d <<< $(head -n 1 $f) #parse date
    DIR="zim/20$y/$m"
    mkdir -p $DIR
    #format title and copy
    sed -e "s/^\([0-9]*-[0-9]*-[0-9]*\)$/====== \\1 ======/" $f> $DIR/$d.txt
done

```

**Comment by Nick222** [comment]
When it see year in text in start of line ("2017 - year of ...") it make it new year...
It create this folder-tree:
20
201917
202015

**Comment by Nick222** [comment]
I think it simpler do it from HTML - where each day is <h1>Четверг, 09.06.2011</h1>

**Comment by Nick222** [comment]
I use CherryTree to convert data from RedNotebook and then to Zim (but attachments cannot convert).

**Comment by hellocatfood** [comment]
Can you please describe this process for the benefit of myself and other users?

**Comment by Nick222** [comment]
RedNotebook store data in month-files, Zim - in one-note-files.

Open RedNotebook files in Cherrytree - and then export it in some text files (not in one file).
Create Zim-notebook and add this text files in it`s subfolder.
Then open Zim and edit it in it.
