### ISSUE TITLE
Tar.gz's on the webpage not extractable?

### ISSUE THREAD

**Issue by JohnCC330** [jaap-karssenberg/zim-desktop-wiki#290]
Before I found the github page, I tried to download the tar.gz's for version 0.67 and 0.68rc1 from the webpage. tar xvf hangs, and mc (midnight commander) reports 'cannot be extracted'.

Downloaded and unpacked from github, but you might want to check the homepage version.

Thanks for the good work.

**Comment by Self-Perfection** [comment]
Works fine for me:
```
$ curl -s http://zim-wiki.org/downloads/zim-0.67.tar.gz | tar -tz | head
zim-0.67/
zim-0.67/contrib/
zim-0.67/contrib/zim2trac.py
zim-0.67/setup.py
zim-0.67/test.py
zim-0.67/cgi-bin/
zim-0.67/cgi-bin/zim.cgi
zim-0.67/icons/
zim-0.67/icons/zim16.png
zim-0.67/icons/zim.ico
```
Check if your file is correctly downloaded:
```
$ curl -s http://zim-wiki.org/downloads/zim-0.67.tar.gz | md5sum
e87975727f1166c723912c949bea51f2  -
$ curl -sI http://zim-wiki.org/downloads/zim-0.67.tar.gz | grep Length
Content-Length: 2034747
```

**Comment by jonasstein** [comment]
I can confirm that my firefox 57.0.4 download returns 
`md5sum ~/Desktop/zim-0.67.tar.gz d91e34f891e7871f9b38881f20ef6cae`
`size with ls: 2035935`

but it is fine with wget. This is spooky. @JohnCC330 was it the same for you?

**Comment by Self-Perfection** [comment]
@jonasstein that's good that you tested with Firefox, I have not checked that.

Apparently the server is misconfigured and compresses any content, even already compressed gz files, if client provides header `Accept-Encoding: gzip`, that's what browser's do by default, but not curl. So downloaded file becomes *double-compressed*. Here is what I had to do to get to contents of archive downloaded with Firefox:

```
$ gzip -cd zim-0.67.tar.gz | gzip -cd | tar -tv | head
drwxrwxr-x jaap/jaap         0 2017-07-10 14:18 zim-0.67/
drwxrwxr-x jaap/jaap         0 2017-07-10 14:18 zim-0.67/contrib/
-rw-rw-r-- jaap/jaap      4955 2017-04-28 12:17 zim-0.67/contrib/zim2trac.py
-rwxrwxr-x jaap/jaap      9923 2017-07-10 09:50 zim-0.67/setup.py
-rwxrwxr-x jaap/jaap      5196 2017-07-04 20:28 zim-0.67/test.py
drwxrwxr-x jaap/jaap         0 2017-07-10 14:18 zim-0.67/cgi-bin/
-rw-rw-r-- jaap/jaap      1276 2017-04-28 12:17 zim-0.67/cgi-bin/zim.cgi
drwxrwxr-x jaap/jaap         0 2017-07-10 14:18 zim-0.67/icons/
-rw-rw-r-- jaap/jaap       857 2017-04-28 12:17 zim-0.67/icons/zim16.png
-rw-rw-r-- jaap/jaap     44278 2017-04-28 12:17 zim-0.67/icons/zim.ico
```

**Comment by JohnCC330** [comment]
On Mon, 15 Jan 2018 04:54:26 +0000 (UTC)
Jonas Stein <notifications@github.com> wrote:

> but it is fine with wget. This is spooky. @JohnCC330 was it the same
> for you?

Yep. I never got around to checking it, but I suspect that the file is
not marked correctly as something that can be binary (MIME type), which
makes the download file fail.

John

**Comment by jaap-karssenberg** [comment]
Closing for now. Website is very simple file upload + static HTML linking to the files. So nothing I can change there. If problem persists I will need to get backoffice of the hosting company to look into it.

**Comment by jonasstein** [comment]
Seems the provider fixed it in the meantime:
 Downloaded now again with Firefox 61 and got
`md5sum zim-0.67.tar.gz  e87975727f1166c723912c949bea51f2  zim-0.67.tar.gz`
