### ISSUE TITLE
Sub-page behavior changed between 0.65 and 0.67

### ISSUE THREAD

**Issue by B-z-F** [jaap-karssenberg/zim-desktop-wiki#293]
Creating link on Home page:
```
Link to: .Test (note the dot on beginning)
Text: Test
```

Then writing some text on Test page and creating another link:
```
Link to: .Sub-test (note the dot on beginning)
Text: Sub-test
```
And then writing some text on Sub-test page result with 0.65 to this file structure:
```
.
└── Notebooks
    └── Notes
        ├── Home
        │   ├── Test
        │   │   └── Sub-test.txt
        │   └── Test.txt
        ├── Home.txt
        └── notebook.zim
```
Same steps result with 0.67 to:
```
.
└── Notebooks
    └── Notes
        ├── Home.txt
        ├── notebook.zim
        ├── Sub-test.txt
        └── Test.txt
```
(checksum of the files in those two examples are after removing date of creation same)

This brokes existing notebooks after upgrade.

**Comment by B-z-F** [comment]
Using period was regular way to create SubPage as of 2010 when I've started using zim and I've not noticed the change to plus sign:
[archive.org - 20100115130103 ](https://web.archive.org/web/20100115130103/http://www.zim-wiki.org/manual/Help/Links.html)
`Links that start with a '.' are resolved in the namespace below the current page`
[archive.org - 20101129173934](https://web.archive.org/web/20101129173934/http://zim-wiki.org/manual/Help/Links.html)
`Links that start with a '+' are resolved in the namespace below the current page`

I'll write script to replace `[[.` to `[[+` in my notebooks and fix my problem.
Thanks for pointing me to solution.

**Comment by Osndok** [comment]
I'm glad to help, interested to know of this zim factoid, and happily salute the more veteran zim-user than myself!
