### ISSUE TITLE
indentation in saved file problem

### ISSUE THREAD

**Issue by MarekLew** [jaap-karssenberg/zim-desktop-wiki#295]
on windows I have problem for zim version 0.67

zim wrong save format document. Ident for next checkbox is deleted where back line not have checkbox.

screen:
![zim](https://user-images.githubusercontent.com/6560667/35093929-09e19e6a-fc44-11e7-8a74-508e87f77c37.png)

If line started checkbox bullet  or other list the problem not exist.

**Comment by jaap-karssenberg** [comment]
Sorry, but your description is to cryptic for me. Can give a detailed example.

Be aware that checkboxes are list items and indented lines are paragraphs, that may confuse the behavior in your case.

**Comment by MarekLew** [comment]
Screen show detali. On the right is source file. when I open such a file again, the 'dfgdfgfgs' indent disappears.

I solved the problem using bullet list instead of indentation.

**Comment by jaap-karssenberg** [comment]
I think bullet list is the right format here, since you are trying to format the text as a list. Indented paragraphs break the list and lead to unexpected behavior here.

**Comment by MarekLew** [comment]
"Indented paragraphs break the list and lead to unexpected behavior here." . This not have sense. It is a bug  indent in list. Indent wrong saved to file
