### ISSUE TITLE
set default pathbar viewing mode

### ISSUE THREAD

**Issue by Tercus** [jaap-karssenberg/zim-desktop-wiki#297]
I seem to be unable to set a default viewing mode for the pathbar. I open a zim wiki and the pathbar always shows "Recent pages". Changing it to "Page Hierarchy" doesn't _stick_ to the next restart. So I have to change it every time I open a zim wiki.

Is there any config I can change, so that the default viewing mode is Page Hierarchy?

**Comment by Osndok** [comment]
The pathbar config is stored per-repo alongside the index database. If Zim does not have permission to write to your home directory, then it might not be saving it properly.

Look for a file along this pattern:
* ```~/.cache/zim/notebook-home_${USERNAME}_${NOTEBOOKNAME}/state.conf```

It is effectively an INI file, and under the ```[MainWindow]```, there is a ```pathbar_type``` entry... the one you want is ```path```.

**Comment by Tercus** [comment]
It was able to create the necessary folder and files (new linux, new zim installation, opened old zim wiki), so it should also be able to write to that file, no?

How can I check if zim fails to write to that location?

**Comment by Osndok** [comment]
I would launch zim with the debug flag ("zim --debug") and look for diagnostic messages upon selecting the view option. Also, it might be worthwhile to check for a ".zim" folder in the notebook directory, as the state.conf might actually be intended for that spot.

**Comment by jaap-karssenberg** [comment]
Working correctly in my testing with master branch, please test with the to-be-released version 0.70 and re-open this issue if the problem persists.
