### ISSUE TITLE
Duplicate entries when using underscore

### ISSUE THREAD

**Issue by Pfeil** [jaap-karssenberg/zim-desktop-wiki#298]
I've been using Zim since a few ubuntu versions, but since Ubuntu 17.10 I noticed a new behavior, and I am not sure if this is just a new default. I often use Numbers and underscores to influence the order of the pages. But now when I do, I first get one entry, but as soon as I save one of them, there appears a second one (without underscore but a space like it should), but the old one does not disappear. I did not find any setting for this, so thats why I am here. First, Screenshot:
![zimbug](https://user-images.githubusercontent.com/4805153/35278369-106fd7d8-004a-11e8-9961-7046cd9e2db9.png)
As you can see, there are still "raw" entries for all existing pages. I used the Version that ships with Ubuntu 17.10 first and now use the ppa, but it did not change anything. So, currently I am using 0.68-rc1 on this computer.

Is this a bug or can I turn this off somehow?

**Comment by Osndok** [comment]
Sounds like #183 & #215 ... if you are feeling adventurous, you might try 0.68-rc1 or the latest master commit.

**Comment by Pfeil** [comment]
It's defenitely #183 , sorry I must have missed it somehow. I tried it using 0.68-rc1 from the ppa and the bug is definitely still there. I will maybe find the time to check out master, but not right now.

**Comment by Pfeil** [comment]
I recreated all links in my current notebook to fix it. It could get a lot of work when having many links. Anyway, thanks for everything :)

**Comment by jaap-karssenberg** [comment]
With 0.68-rc1 or newer run "zim --index" to force re-indexing the links should work as well.
