### ISSUE TITLE
Source View: support for additional languages

### ISSUE THREAD

**Issue by digilur** [jaap-karssenberg/zim-desktop-wiki#299]
I would love syntax support for VimL and json syntax in code blocks. What would this take? XML language definition files for gtksourceview-2.0?

**Comment by jonasstein** [comment]
@digilur you could try to parse it with Pygments http://pygments.org/

**Comment by genodeftest** [comment]
Please report this against [GtkSourceView](https://wiki.gnome.org/Projects/GtkSourceView), which is the widget Zim is using for displaying code.

**Comment by jaap-karssenberg** [comment]
Current plugin indeed uses gtksourceview, so any request for language support should go upstream to that component and zim will benefit as well.

**Comment by digilur** [comment]
Understood, thanks.
