### ISSUE TITLE
Zim Help /Bugs directed me to launchpad

### ISSUE THREAD

**Issue by colemanc** [jaap-karssenberg/zim-desktop-wiki#300]
I reported a bug using the link inside Zim Help which took me to launchpad where I reported a bug. However I do not think that is the proper location for bug reporting anymore since issues there "new" seem very old. Should the help link in Zim point to here instead?

**Comment by Self-Perfection** [comment]
This is a duplicate of #180 and already resolved by https://github.com/jaap-karssenberg/zim-desktop-wiki/commit/816ff9ff14fa52769daebbb12e476fe2145b2ed2

**Comment by colemanc** [comment]
Yes. Sorry. I did not check for this in the backlog. I installed zim from using synaptic in ubuntu in December so I am not sure contains this fix. I will look into updating my software. Thank you!
