### ISSUE TITLE
Package as flatpak

### ISSUE THREAD

**Issue by thecursedfly** [jaap-karssenberg/zim-desktop-wiki#302]
It would be great if Zim could be packaged also as a **flatpak**, so that most/all Linux distributions can easily get the latest version without delays, distro-specific or dependency issues, and the added security of sandboxing.
For documentation, please see: [http://docs.flatpak.org/en/latest/](http://docs.flatpak.org/en/latest/)

**Comment by cheese** [comment]
I am the Fedora packager for Zim and recently start learning Flatpak and trying to make Zim as my first flatpak.
The actual package is done. Though Zim uses the id 'org.zim-wiki.Zim' in appdata, so the same ID should be used as flatpak ID. But flatpak allows only the last part of ID contains '-' character. I am going to ask a solution in flatpak mailing list.

Here is my current draft of flatpak-builder json for Zim. Flatpak ID is 'org.zim_wiki.Zim' in this draft.

<pre>
{
    "app-id": "org.zim_wiki.Zim",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.26",
    "sdk": "org.gnome.Sdk",
    "command": "zim",
    "rename-desktop-file": "zim.desktop",
    "rename-icon": "zim",
    "finish-args": [
        /* X11 + XShm access */
        "--share=ipc", "--socket=x11",
        /* libappindicator access */
        "--socket=session-bus",
        "--filesystem=host",
        "--filesystem=~/.config/zim:create"
    ],
    "modules": [
        {
            "name": "py2cairo",
            "rm-configure": true,
            "sources": [
                {
                    "type": "archive",
                    "url": "http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2",
                    "sha256": "d30439f06c2ec1a39e27464c6c828b6eface3b22ee17b2de05dc409e429a7431"
                },
                {
                    "type": "script",
                    "commands": [
                        "libtoolize --force",
                        "aclocal",
                        "autoheader",
                        "automake --force-missing --add-missing --foreign",
                        "autoconf"
                    ],
                    "dest-filename": "autogen.sh"
                }
            ]
        },
        {
            "name": "pygobject2",
            "sources": [
                {
                    "type": "archive",
                    "url": "http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.7.tar.xz",
                    "sha256": "bb9d25a3442ca7511385a7c01b057492095c263784ef31231ffe589d83a96a5a"
                }
            ]
        },
        {
            "name": "pygtk2",
            "sources": [
                {
                    "type": "archive",
                    "url": "http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2",
                    "sha256": "cd1c1ea265bd63ff669e92a2d3c2a88eb26bcd9e5363e0f82c896e649f206912"
                }
            ]
        },
        {
            "name": "pyxdg",
            "buildsystem": "simple",
            "build-commands": [
                "python2 setup.py install --prefix=/app"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "http://people.freedesktop.org/~takluyver/pyxdg-0.25.tar.gz",
                    "sha256": "81e883e0b9517d624e8b0499eb267b82a815c0b7146d5269f364988ae031279d"
                }
            ]
        },
        {
            "name": "pygtksourceview",
            "sources": [
                {
                    "type": "archive",
                    "url": "http://download.gnome.org/sources/pygtksourceview/2.10/pygtksourceview-2.10.1.tar.bz2",
                    "sha256": "b4b47c5aeb67a26141cb03663091dfdf5c15c8a8aae4d69c46a6a943ca4c5974"
                }
            ],
            "modules": [
                {
                    "name": "gtksourceview2",
                    "config-opts": ["--enable-introspection=no"],
                    "sources": [
                        {
                            "type": "archive",
                            "url": "http://download.gnome.org/sources/gtksourceview/2.11/gtksourceview-2.11.2.tar.bz2",
                            "sha256": "f9594d8f18f6bcc3d72da4051636d7a8b4d3f6d29d6827309b262c9483644994"
                        },
                        {
                            "type": "patch",
                            "path": "0001-Force-gtk2.patch"
                        },
                        {
                            "type": "patch",
                            "path": "gtksourceview-2.11.2-cflags.patch"
                        },
                        {
                            "type": "patch",
                            "path": "gtksourceview-2.11-fix-GCONST-def.patch"
                        },
                        {
                            "type": "patch",
                            "path": "gtksourceview-2.11-add-libs.patch"
                        },
                        {
                            "type": "patch",
                            "path": "gtksourceview-2.11-glib-unicode-constant.patch"
                        }
                    ]
                }
            ]
        },
        {
            "name": "libappindicator",
            "config-opts": [ "-disable-static", "--disable-tests", "--disable-gtk-doc", "--enable-introspection=no", "--with-gtk=2"],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://launchpad.net/libappindicator/12.10/12.10.0/+download/libappindicator-12.10.0.tar.gz",
                    "sha256": "d5907c1f98084acf28fd19593cb70672caa0ca1cf82d747ba6f4830d4cc3b49f"
                }
            ],
            "modules": [
                {
                    "name": "gnome-doc-utils",
                    "sources": [
                        {
                            "type": "archive",
                            "url": "http://ftp.gnome.org/pub/GNOME/sources/gnome-doc-utils/0.20/gnome-doc-utils-0.20.10.tar.xz",
                            "sha256": "cb0639ffa9550b6ddf3b62f3b1add92fb92ab4690d351f2353cffe668be8c4a6"
                        }
                    ]
                },
                {
                    "name": "libdbusmenu",
                    "config-opts": [ "--with-gtk=2", "-disable-static", "--disable-tests", "--disable-gtk-doc", "--disable-doc", "--disable-dumper", "--enable-introspection=no", "--disable-vala", "--enable-gtk-doc=no"],
                    "build-options" : {
                        "env": {
                            "HAVE_VALGRIND_TRUE": "'#'",
                            "HAVE_VALGRIND_FALSE": "''"
                        }
                    },
                    "sources": [
                        {
                            "type": "archive",
                            "url": "https://launchpad.net/libdbusmenu/12.10/12.10.2/+download/libdbusmenu-12.10.2.tar.gz",
                            "sha256": "9d6ad4a0b918b342ad2ee9230cce8a095eb601cb0cee6ddc1122d0481f9d04c9"
                        }
                    ]
                },
                {
                    "name": "libindicator",
                    "config-opts": [ "--with-gtk=2", "-disable-static", "--disable-tests", "--disable-gtk-doc"],
                    "sources": [
                        {
                            "type": "archive",
                            "url": "https://launchpad.net/libindicator/12.10/12.10.1/+download/libindicator-12.10.1.tar.gz",
                            "sha256": "b2d2e44c10313d5c9cd60db455d520f80b36dc39562df079a3f29495e8f9447f"
                        },
                        {
                            "type": "shell",
                            "commands": [
                                  "sed '/-Werror/s/$/ -Wno-deprecated-declarations/' -i libindicator/Makefile.{am,in}",
                                  "sed 's/LIBINDICATOR_LIBS+=\"$LIBM\"/LIBINDICATOR_LIBS+=\" $LIBM\"/g' -i configure",
                                  "sed 's/LIBM=\"-lmw\"/LIBM=\" -lmw\"/g' -i configure",
                                  "sed 's/LIBM=\"-lm\"/LIBM=\" -lm\"/g' -i configure",
                                  "sed 's/LIBS=\"-lm  $LIBS\"/LIBS=\" -lm  $LIBS\"/g' -i configure",
                                  "sed 's/LIBS=\"-lmw  $LIBS\"/LIBS=\" -lmw  $LIBS\"/g' -i configure"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name": "zim",
            "buildsystem": "simple",
            "build-commands": [
                "python2 setup.py build",
                "python2 setup.py install --prefix=/app --skip-xdg-cmd --skip-build",
                "mkdir -p /app/share/appdata",
                "sed -i s/zim-wiki/zim_wiki/g /app/share/metainfo/org.zim-wiki.Zim.metainfo.xml",
                "cp /app/share/metainfo/org.zim-wiki.Zim.metainfo.xml /app/share/appdata/org.zim_wiki.Zim.appdata.xml",
                "mv /app/share/metainfo/org.zim-wiki.Zim.metainfo.xml /app/share/metainfo/org.zim_wiki.Zim.metainfo.xml"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "http://zim-wiki.org/downloads/zim-0.68-rc1.tar.gz",
                    "sha256": "3c58aaceeceed1a35b3260254384e3bbfbc03c9be4db87dc47723f161f9d1950"
                }
            ]
        }
    ]
}
</pre>

**Comment by cheese** [comment]
Flatpak mailing list suggested to change id to 'org.zim_wiki.Zim', as what I have supposed to.
https://lists.freedesktop.org/archives/flatpak/2018-January/000928.html
PR: https://github.com/jaap-karssenberg/zim-desktop-wiki/pull/307

**Comment by cheese** [comment]
Flatpak of Zim is now available in flathub as org.zim_wiki.Zim.
