### ISSUE TITLE
Verbatim text

### ISSUE THREAD

**Issue by IvanC000** [jaap-karssenberg/zim-desktop-wiki#321]
So happy to have discovered wiki. I only have a problem. I would like that the verbatim text paragraphs would go no further right than other normal text paragraphs. I have been trying, but I cannot find the way to achieve that. 
Thank you.

**Comment by Self-Perfection** [comment]
Set `wrap-mode` for `pre` tag to `GTK_WRAP_WORD`. That is changed in `style.conf` (see doc on [config files](http://zim-wiki.org/manual/Help/Config_Files.html)).

**Comment by IvanC000** [comment]
Thanks a lot.

**Comment by reagle** [comment]
A bit more explicitly for those coming across this:

	[Tag code]
	foreground=#2e3436
	family=monospace
	wrap-mode=GTK_WRAP_WORD
	indent=-30

	[Tag pre]
	foreground=#2e3436
	family=monospace
	wrap-mode=GTK_WRAP_WORD
	indent=-30
