### ISSUE TITLE
some issues with windows version 0.66 

### ISSUE THREAD

**Issue by herbrot** [jaap-karssenberg/zim-desktop-wiki#33]
first of all many thanks for your great work - I really love the program

there are some behavior changes in the Windows Version 0.66 (Windows 7 / Windows Server 2012)
1. Text can no more selected with mouse click on a word
2. selected can not be copied to another program / only in zim it self
3. double click in attachment browser pane does no more open the document

4. Checkbox lists appear in the tasklist regardless the Settings in the plugin configuration
(the setting [>] let them disappear as work araound)

**Comment by jaap-karssenberg** [comment]
Please only report 1 issue per "issue" otherwise our administration becomes too complex. Also please chekc for existing reports that cover your problem and add your information.
