### ISSUE TITLE
Gtk3: visual check all windows and dialogs

### ISSUE THREAD

**Issue by jaap-karssenberg** [jaap-karssenberg/zim-desktop-wiki#336]
Since packing of widgets has slightly changed in Gtk3, we need to visually check all windows and dialogs for glitches in the rendering. Make sure te resize dialogs to see if widgets behave in a sane way on resize as well.

- [x] MainWindow
- [x] PageWindow
- [x] ServerWindow
- [x] InsertScreenshotDialog
- [x] QuickNoteDialog
- [x] JournalMainWindowExtensionDialog
- [x] CalendarDialog
- [x] EditTableDialog
- [x] ImageGeneratorDialog
- [x] InsertSymbolDialog
- [x] LinkMapDialog
- [x] InsertCodeBlockDialog
- [x] VersionControlInitDialog
- [x] SaveVersionDialog
- [x] VersionsDialog
- [x] TextDialog
- [x] TaskListDialog
- [x] PropertiesDialog
- [x] SavePageErrorDialog
- [x] InsertDateDialog
- [x] InsertImageDialog
- [x] AttachFileDialog
- [x] EditImageDialog
- [x] InsertTextFromFileDialog
- [x] InsertLinkDialog
- [x] FindAndReplaceDialog
- [x] WordCountDialog
- [x] MoveTextDialog
- [x] NewFileDialog
- [x] RecentChangesDialog
- [x] SearchDialog
- [x] CustomizeOpenWithDialog
- [x] AddApplicationDialog
- [x] ErrorDialog
- [x] QuestionDialog
- [x] MessageDialog
- [x] FileDialog
- [x] ProgressDialog
- [x] LogFileDialog
- [x] TemplateEditorDialog
- [x] PromptNameDialog
- [x] NewPageDialog
- [x] ImportPageDialog
- [x] SaveCopyDialog
- [x] RenamePageDialog
- [x] MovePageDialog
- [x] DeletePageDialog
- [x] AttachFileDialog
- [x] PromptExistingFileDialog
- [x] MyAboutDialog
- [x] CustomToolManagerDialog
- [x] EditCustomToolDialog
- [x] NotebookDialog
- [x] AddNotebookDialog
- [x] ExportDialog
- [x] ExportDoneDialog
- [x] OpenPageDialog
- [x] PreferencesDialog
- [x] PluginConfigureDialog

**Comment by muguu** [comment]
Checked following as ok:

- [x] CalendarDialog 

- [ ] AttachFileDialog
- Button text "gtk-open"  instead of "Open"
- "Insert picture as link" checkbox missing
- Resizing of Columns "Name" and Location" to Zero instead of Column Title size
- Sorting for Name and Location does not possible

**Comment by muguu** [comment]
- [ ] SearchDialog
- Treeview size not correct
`gtk-Critical: gtk_widget_get_preffered_width_for_height:assertion...`

**Comment by muguu** [comment]
- [ ] NotebookDialog
- Notebook treeview size too small

- [ ] AddNotebookDialog
- Positioning of Dialog is wrong (does not open above parent)
- Positioning of "Select Folder" Dialog is wrong
- Child dialogs are not modal and don't prevent creating multiple "Add Notebook" dialogs (Add button)

______________________________
