### ISSUE TITLE
Add '>' as another bullet type for comments as sub-bullet for tasks

### ISSUE THREAD

**Issue by muguu** [jaap-karssenberg/zim-desktop-wiki#34]
Could you add '>' as another bullet type? May be with the option to replace this with an icon (gtk.STOCK_DND)

This could be used to add comments to a task and look more nicely.

Thank you and Regards,
Murat

**Comment by jaap-karssenberg** [comment]
Can I translate your request as "please support quoted paragraphs" ?  Reason is that I would not consider this a bullet, but a paragraph.

For comparison, see the "blockquote" support in markdown, is this what you mean? https://daringfireball.net/projects/markdown/syntax#blockquote

**Comment by sojusnik** [comment]
[Blockquotes](https://daringfireball.net/projects/markdown/syntax#blockquote) FTW :D

**Comment by muguu** [comment]
My request is motivated through my work on the task list enhancements I did for zim 0.65.

I collect the comments below tasks which were added by the task comment plugin to show within the task list window next to a task in a separate column.

For this, I look for the comment string to identify a comment. Also the comment line is set as a bullet with a bullet icon.

So a task with a comment line can look like this:

[ ] This is a task
- [comment:2017-05-13] > This is a comment to the task

I tried to recuce the comment to something like:
[ ] This is a task
">"[2017-05-13] This is a comment to the task ....( ignore the quotation mark here. Just added them to display > )

To properly identify the comment, I think it would be helpful to have ">" as another bullet type.
I tried myself, but wasn't completly successful so far. As you already added another bullet type, I thought it could be quite easy to do another.

With regards to a blockquote, I think a bullet would be the quickest way to support basic blockquotes.
As I can't find a use case for myself for block quotes within Zim, I can't really judge if it would make sense to fully implement block quotes.

**Comment by jaap-karssenberg** [comment]
For me a "quote" means you quote someone else, e.g. you copied part of an
email send by someone to you. This is the use case for the blockquote and
the conventional use of ">" in emails and other wikis.

If you talk about "comments" I understand that to be your own comments on
an item. So I would not want to use the same ">" symbol for that,

Furthermore this also drives the implementation. Quotes from other people
are typically "blocks", i.e. sections that contain paragraphs, lists,
images etc. A single bullet as a quote doesn't really make sense. If you
quote a single sentence you typically quote using ".." quotes.

Maybe my biggest question is this: why do comments need a separate bullet
type at all? Why not just put comments as new sub-bullets with a date - why
do they need a special marker ?

Regards,

Jaap

**Comment by muguu** [comment]
Ok, with your explanations, I don't think that "quote" is the right type for my request.

The original idea behind the task comment plugin was to have a place to add additional information to an existing task without changing the original task text.

For this a sub-bullet is totally useful and ok. 

While looking into the collection of the comments for a task to display them within the task list plugin dialog, I was happy to identify a comment as a bullet below a task.

Since the task bullet is displayed as a pixbuf, and since a comment is an essential part of a task in my eyes, I think it would make sense to display comments also as a pixbuf (e.g. gtk.STOCK_DND).
From my investigations of the pageview module, I think an own bullet type is needed to accomplish that.

I don't insist on ">" and could imagine something like (c) or [c] (tc) or [tc] as well, but (c) is reserved for copyright, isn't it?

Regards,
Murat

**Comment by jaap-karssenberg** [comment]
> The original idea behind the task comment plugin was to have a place to add additional information to an existing task without changing the original task text.

For me a sub-bullet signals this information belongs to the task, and you don't modify the task itself. By inserting the date you already show this comment was added at some later point in time. So still don't see much reason why it would need a new bullet type or image at all, just "*" would work for me.

For example:

```
[ ] Call susan re diner party @phone <2017-06-01
    * Discuss who to invite
    * Discuss what to cook
    * 2017-05-15: tried to call, but she is on holiday, try again next week
```

Here the first two sub-bullets are part of the original task and the third one is later added as a comment. To me this is perfectly readable without a special bullet type.

Regards,

Jaap
