### ISSUE TITLE
Gtk3: improve style of statusbar in mainwindow

### ISSUE THREAD

**Issue by jaap-karssenberg** [jaap-karssenberg/zim-desktop-wiki#342]
The statusbar at the bottom of the mainwindow used to be rendered small, but now takes full size + a border. At least remove the border, check what else can be done to reduce the size a bit.

**Comment by genodeftest** [comment]
When I use Zim, this issue is caused by the `zim.gui.mainwindow.BackLinksMenuButton` being quite high because it hosts a `GtkToggleButton`.

**Comment by genodeftest** [comment]
Another cause is the huge `margin` of 10px on `Gtk.StatusBar`. This is not a CSS margin, i.e. setting
```
statusbar {
	margin: 0px
}
```
does not solve the issue. The margin cannot be changed by setting `self.statusbar.margin = 0` around zim.gui.mainwindow:L185 either, this seems to be ignored. `self.statusbar.set_property()` works fine though. I'll attach a patch to #354.
