### ISSUE TITLE
Gtk3: double click on window decoration in fullscreen under Gnome3

### ISSUE THREAD

**Issue by jaap-karssenberg** [jaap-karssenberg/zim-desktop-wiki#343]
Double click on window decoration in fullscreen under Gnome3 does not work as expected. The window does not toggle to non-fullscreen size as expected.

By comparison, double click to go from small size to fullscreen does work.

Sounds like something the desktop environment should manage, but double check zim does not somehow block this logic by handling of signals for window size changes.

**Comment by genodeftest** [comment]
Dragging the window down works fine. Right-click -> Un-maximize works fine too. Looks like an issue in Zim to me.
