### ISSUE TITLE
Gtk3: pageview.py throws TypeError

### ISSUE THREAD

**Issue by muguu** [jaap-karssenberg/zim-desktop-wiki#348]
After I start zim.py (as root), following TypeError is shown continuously.

Could be related to #347 though, as the setup of next-build has not been processed and master-build- 68rc1 is installed in parallel.

```
Traceback (most recent call last):
  File "/home/murat/zim-desktop-wiki-next/zim/gui/pageview.py", line 3602, in on_motion_notify_event
    self.update_cursor(coords)
  File "/home/murat/zim-desktop-wiki-next/zim/gui/pageview.py", line 4044, in update_cursor
    ok, iter = self.get_iter_at_location(*coords)
TypeError: 'TextIter' object is not iterable
```

**Comment by muguu** [comment]
Mouse is not working: I can't position the cursor or select any text.

**Comment by jaap-karssenberg** [comment]
Can;t reproduce this item, not sure what is different in your install

In general I would never run user programs as zim with root

**Comment by muguu** [comment]
Seems to be related to my LinuxMint installation.
On a fresh Ubuntu installation, the error does not occur any more.
