### ISSUE TITLE
Action open_attachments_folder causes exception in V0.66 and V0.67RC1

### ISSUE THREAD

**Issue by mnordlin** [jaap-karssenberg/zim-desktop-wiki#35]
This exception started with V0.66, it was not present in 0.65, and has not been dealt with by the commits to 0.67RC1, where similar file handling stuff was fixed. The bug affects source and Windows builds equally.
(There is a difference between versions 0.66 and 0.67RC1 in how Windows (I'm on Win 10 x64) locales are dealt with. In 0.65 the menus were all in English, in 0.66 in German, and in 0.67RC1 they're back to English. I'm fine with that, so no problem. I just thought I'd mention it in case it's related.)
debug log (slightly edited):
C:\Program Files (x86)\zim-0.67-rc1>python zim.py --debug
INFO: Locale set to: de_DE.cp1252
INFO: This is zim 0.66
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
DEBUG: Platform is nt
DEBUG: No bzr version-info found
DEBUG: Running from a source dir: C:\Program Files (x86)\zim-0.67-rc1
DEBUG: Set XDG_DATA_HOME to C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\data
DEBUG: Set XDG_DATA_DIRS to [<Dir: C:\Users\Mikael.DESKTOP-7K2LJVT\.local\share>]
DEBUG: Set XDG_CONFIG_HOME to C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: C:\Users\Mikael.DESKTOP-7K2LJVT\.config>]
DEBUG: Set XDG_CACHE_HOME to C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\cache
DEBUG: Connecting to \\.\pipe\zim-Mikael-0.66-e167ad56-primary
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Registered object line
DEBUG: Starting primary process
DEBUG: Start listening on: \\.\pipe\zim-Mikael-0.66-e167ad56-primary
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x04102B30>
DEBUG: Loading config from: N:\Wiki\notebook.zim
DEBUG: Wrote C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\config\zim\notebooks.list
INFO: Using default notebook: file:///N:/Wiki
DEBUG: Loading config from: N:\Wiki\notebook.zim
DEBUG: Wrote N:\Wiki\.zim.tmp
INFO: Remove file: N:\Wiki\.zim.tmp
DEBUG: Opening notebook: <zim.notebook.notebook.Notebook object at 0x04E93CD0>
DEBUG: Loading config from: <ConfigFile: C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\config\zim\preferences.conf>
DEBUG: Loading plugin: attachmentbrowser
DEBUG: Loading plugin: autocompletion
DEBUG: Loading plugin: backlinkpane
DEBUG: Loading plugin: bookmarksbar
DEBUG: Loading plugin: calendar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: quicknote
DEBUG: Loading plugin: screenshot
DEBUG: Loading plugin: search_tagged_pages
DEBUG: Loading plugin: sourceview
DEBUG: Registered object code
DEBUG: Loading plugin: tags
DEBUG: Loading plugin: tasklist
DEBUG: Gtk version is (2, 24, 10)
DEBUG: Pygtk version is (2, 24, 0)
DEBUG: Loading config from: <ConfigFile: C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\config\zim\style.conf>
DEBUG: Loading config from: C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\cache\zim\notebook-N_Wiki\state.conf
C:\Program Files (x86)\zim-0.67-rc1\zim\plugins\__init__.py:762: GtkWarning: Inserting action group 'MainWindowExtension' into UI manager which already has a group with this name

  self.window.uimanager.insert_action_group(actiongroup, 0)
C:\Program Files (x86)\zim-0.67-rc1\zim\gui\__init__.py:2302: GtkWarning: open_page_back_alt1: missing action open_page_back_alt1
  self.uimanager.ensure_update()
C:\Program Files (x86)\zim-0.67-rc1\zim\gui\__init__.py:2302: GtkWarning: open_page_forward_alt1: missing action open_page_forward_alt1
  self.uimanager.ensure_update()
DEBUG: Accelmap: C:\Users\Mikael.DESKTOP-7K2LJVT\AppData\Roaming\zim\config\zim\accelmap
INFO: Open page: Home:Advokat:Client:Verschleiert:Verschleiert2 (Home:Advokat:Client:Verschleiert:Verschleiert2)
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: N:\Wiki
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: N:\Wiki\Home\Advokat\Client\Verschleiert
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: N:\Wiki\Home\Phone\Devices\Cell_Phones\Software
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: N:\Wiki\Home\Phone\Devices\Cell_Phones\Software\OS\Android\NetGuard
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: N:\Wiki\Home\Computer\Software\Zim_Desktop_Wiki
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: open_attachments_folder
DEBUG: open_file(<zim.notebook.layout.FilesAttachmentFolder object at 0x040DFA90>, None)
ERROR: Exception during action: open_attachments_folder
Traceback (most recent call last):
  File "C:\Program Files (x86)\zim-0.67-rc1\zim\actions.py", line 149, in do_activate
    self.__get__(instance, instance.__class__)()
  File "C:\Program Files (x86)\zim-0.67-rc1\zim\actions.py", line 132, in func
    self.func(instance, *args, **kwargs)
  File "C:\Program Files (x86)\zim-0.67-rc1\zim\gui\__init__.py", line 1360, in open_attachments_folder
    self.open_dir(dir)
  File "C:\Program Files (x86)\zim-0.67-rc1\zim\gui\__init__.py", line 1215, in open_dir
    self.open_file(dir)
  File "C:\Program Files (x86)\zim-0.67-rc1\zim\gui\__init__.py", line 1244, in open_file
    assert isinstance(file, (File, Dir))
AssertionError

**Comment by jaap-karssenberg** [comment]
Fix in 2a38a328dc569b1e783bc64417e4f63ac507f2fa
