### ISSUE TITLE
Uniqueness in pathbar labels

### ISSUE THREAD

**Issue by jaap-karssenberg** [jaap-karssenberg/zim-desktop-wiki#364]
0.68-rc1 wil show second path element in case labels in the pathbar are not unique. This should be increased to show as many parts as necessary to reveal the difference between two pages.

**Comment by Osndok** [comment]
I'm not sure how, but it seems that this commit breaks the "View -> Pathbar -> Recently Changed" feature... as (at least for me) it now only shows an empty pathbar when that option is selected.

**Comment by jaap-karssenberg** [comment]
Good catch !
