### ISSUE TITLE
Gtk3: Traceback on `do_button_release_event()`

### ISSUE THREAD

**Issue by genodeftest** [jaap-karssenberg/zim-desktop-wiki#374]
When using the latest git master, I ran into a bug causing this traceback:
```
do_button_release_event() missing 1 required positional argument: 'event'

TypeError: do_button_release_event() missing 1 required positional argument: 'event'
```

I don't know what caused this issue.

**Comment by jaap-karssenberg** [comment]
Could you verify whether this is still valid in latest master? Looks like all "do_button_release_event()" calls have the right argument at the moment.

**Comment by genodeftest** [comment]
I have not seen this issue in the latest release for a while.
