### ISSUE TITLE
Export Zim-notebook as ODF

### ISSUE THREAD

**Issue by Nick222** [jaap-karssenberg/zim-desktop-wiki#395]
Can user export Zim-notebook as ODF - LibreOffice Writer (ODT) format - and keep structure of notebook and all headings in notes as document outlining (may be through any third format)?

**Comment by 1xPdd** [comment]
You should be able to create a script, then call it as a 'Custom Tool.' Something like:

`zim --export \
  --format=markdown \
  --output="/tmp/$note.md" \
  "$note"

pandoc "/tmp/$note.md" -o "~/Desktop/$note.odt"`

**Comment by Nick222** [comment]
Very good :) OK :)
