### ISSUE TITLE
Poll: Count number of plugin users

### ISSUE THREAD

**Issue by muguu** [jaap-karssenberg/zim-desktop-wiki#438]
This is a more a poll than an issue. 
@jaap-karssenberg If this is not the right place, please tell.

I just wonder which of my plugins are really used. I'd appreciate your participation.

Cheers
Murat

<p><a href="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/tag%20autocompletion/vote"><img src="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/tag%20autocompletion" alt=""></a>
<a href="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/search%20tagged%20pages/vote"><img src="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/search%20tagged%20pages" alt=""></a>
<a href="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/task%20comment/vote"><img src="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/task%20comment" alt=""></a>
<a href="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/theme%20manager/vote"><img src="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/theme%20manager" alt=""></a>
<a href="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/convert2tags2mail/vote"><img src="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/convert2tags2mail" alt=""></a>
<a href="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/tasklist%20with%20tag%20autocompletion/vote"><img src="https://api.gh-polls.com/poll/01CD2R9ZCD22877TC2Y4RFC4F1/tasklist%20with%20tag%20autocompletion" alt=""></a></p>

**Comment by Osndok** [comment]
Perhaps a better title would be "Poll: Which plugins do you use?"... the current title makes it sound like you ask asking Jaap to include some sort of tracking mechanism.

Also... for plugins that are not included with the app, you might be interested in search for zim plugins on github, and viewing there star rating. Perhaps the number of users would be proportional to that?

In regards to this being the proper place... it probably isn't, but I'm not sure there is a proper place for this sort of thing ATM. Best of luck!

**Comment by Self-Perfection** [comment]
@muguu subtract 2 from "tag autocompletion" result - that was accidental click from me and another one in attempt to revert but it just increased score once again.

Tracking mechanism seems to be a good idea, was thinking about it myself. Probably couple of standard plugins are too rarely used and may be ditched.

**Comment by ecodiv** [comment]
I am not sure many people are going to see this poll. I am using tag autocompletion (thanks for your work on that!), and would like to use tasklist with tag autocompletion. But the latter does not seem to (fully) work for Zim 0.68? The autocompletion part does not in my case.

**Comment by muguu** [comment]
@Osndok Thanks. Changed the title.

**Comment by muguu** [comment]
@ecodiv After the update to 0.68, I stopped the work for the tasklist with tag autocompletion as it is quite an effort to migrate. I rather persuade Jaap to add the features as a standard. :)

Speeking of:

+ Autocompletion of tags instead of scrolling through the list to find a tag
+ Collecting comments to a task and displaying them within a separate column
+ Adding ticked date to tasks
+ Showing history of ticked tasks
+ Separation of tags within a task into a separate column
+ Enhance print output

**Comment by Self-Perfection** [comment]
@muguu I don't use any zim plugins other than bundled with standard distribution. Though tag autocompletion sounds interesting, I probably should give your plugin a shot.
