### ISSUE TITLE
Verbatim - Formatting

### ISSUE THREAD

**Issue by rcbeall1** [jaap-karssenberg/zim-desktop-wiki#446]
I love using Zim Wiki to create IT documentation at work.  I use "Verbatim" formatting to format unix commands in my guide.  When I do this with longer commands, it keeps it all on one line and I have to scroll horizontally to see everything (which is fine) but I have noticed that the last few characters of the line is cut off.  When I copy and paste the command block into a text editor, all of the characters are present, so Zim Wiki is not removing the characters, but they are not displaying properly.

**Comment by e3rd** [comment]
Could you maybe send here a test zim page so that we see? :)

**Comment by rcbeall1** [comment]
I removed and re-added zim wiki to my workstation and I am no longer experiencing the issue which is good news!  If the issue comes up again, I will provide an update on this thread :).  Thank you!

**Comment by e3rd** [comment]
So that I recommend to close the issue :)

**Comment by rcbeall1** [comment]
The issue has been closed.  Thank you!
