### ISSUE TITLE
Text formatting simultaneous - bold, italic, monospace, ...

### ISSUE THREAD

**Issue by waldauf** [jaap-karssenberg/zim-desktop-wiki#470]
Hello,
at first I would like to say many thx for your work. I'm using Zim every day and many my colleagues when they see it on my laptop they want it to use also. :]

Can I ask you if is possible to enable to use more formatting stiles simultaneous (together). I would like to have bold and italic, or bold and monospace (not sure if it is verbatim). 

Thx for your answer in advance!

**Comment by Self-Perfection** [comment]
Just a couple of days ago was proposed PR #468 that implements this.

**Comment by waldauf** [comment]
Great news! Thx for your answer.
