### ISSUE TITLE
sourceview is unable to see gtksourceview2 installed on archlinux

### ISSUE THREAD

**Issue by jerome-diver** [jaap-karssenberg/zim-desktop-wiki#482]
from archlinux OS, install zim, then instal gtksourceview2 (together from official repos) and then try to add source view plugin from opened zim. You can not, zim can not see that gtksourceviw2 is allready installed.

**Comment by nicolasm** [comment]
Hi Jérôme,
You need one more package: pygtksourceview2.

**Comment by jerome-diver** [comment]
that's it, perfect, thank you very much.
