### ISSUE TITLE
Unable to open Zim through an SSH X11 tunnel

### ISSUE THREAD

**Issue by jeremyshannon** [jaap-karssenberg/zim-desktop-wiki#498]
Hi, I've experienced a bit of misbehavior from Zim (0.68) regarding SSH tunneling. It seems like Zim disregards the environment's DISPLAY variable and just pops its window up on the local machine's primary X instance when it should be connecting to the SSH tunnel's fake one instead.

**Comment by Osndok** [comment]
I seem to recall running into this, and concluding that it had something to do with it's multi-process architecture (the second 'zim' run sees the first running, and delegates to it).

**Comment by jeremyshannon** [comment]
I suspected that might be happening, so I tried killing all zim processes from the command line and then restarting it, but no joy.

**Comment by Osndok** [comment]
Are you 100% sure you are using x11 on the target machine, and not wayland?

**Comment by jeremyshannon** [comment]
Yep, no Wayland here, just X.org.

**Comment by Self-Perfection** [comment]
Strange, I just tried running zim 0.68 via ssh X tunneling and it worked fine.

Make sure you don't have running zim neither on server nor on client before launching zim via X forwarding.

**Comment by jeremyshannon** [comment]
Okay, I tried it again today, and it worked this time. The only thing I can figure is that maybe I should have added a -9 to the "killall zim" command I sent last time, like maybe it was hung or something.
 Closing this, since it seems to work now.

**Comment by Osndok** [comment]
Ahh.... yes... depending on how you launch the app, ```killall zim``` might not work because the binary is actually ```python```.

I usually issue ```pgrep -fa zim```  and manually/visually pick out the PID from there.
