### ISSUE TITLE
unrecognized {{ characters

### ISSUE THREAD

**Issue by inzagod** [jaap-karssenberg/zim-desktop-wiki#517]
hi,
i want to write in a page a command to remember it :

	- 
	  name: Ludo - current_version
	  debug: var= "{{ current_version }}"

but zim not recognize the {{ and display this instead : 

	- 
	  name: Ludo - current_version
	  debug: var= " an image representing redcross "

how can i fix this issue ?

with simple { it works !

thanks a lot 

ludo

**Comment by Osndok** [comment]
I would recommend putting it in a block quote, which you can start/end with three apostrophes.

e.g.
```
'''
name: Ludo - current_version
debug: var= "{{ current_version }}"
'''
```

**Comment by inzagod** [comment]
thanks a lot it works finhe ! thanks
