### ISSUE TITLE
task-list plugin help page typo

### ISSUE THREAD

**Issue by muguu** [jaap-karssenberg/zim-desktop-wiki#53]
The following statement within the task-list help page is misleading:

> A due date can added by typing ">" followed by a while a start date is given as "<" followed by a date.
For example

Shouldn't it be the other way round?

Due is "<" and
Start is ">" ??

Regards,
Murat

**Comment by jaap-karssenberg** [comment]
I believe this is already fixed in master

**Comment by jaap-karssenberg** [comment]
See a18c063c9b371ac604b9eedb0de1e9146934565e
