### ISSUE TITLE
'database is locked' after continually clicking the trayicon

### ISSUE THREAD

**Issue by cheese** [jaap-karssenberg/zim-desktop-wiki#58]
On Fedora 26, KDE plasma workspace.
git commit 022bfef5b6d55c84832d5f95d8e3e0b111f53864
Tray icon plugin with 'Classic trayicon' checked.

$ ./zim.py -D --standalone
INFO: This is zim 0.66
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: No bzr version-info found
DEBUG: Running from a source dir: /home/cheese/zim-desktop-wiki
DEBUG: Set XDG_DATA_HOME to /home/cheese/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/kde-settings/kde-profile/default/share>, <Dir: /usr/local/share>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/cheese/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg>, <Dir: /usr/share/kde-settings/kde-profile/default/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/cheese/.cache
DEBUG: Registered object line
DEBUG: Starting standalone process
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89bbba4390>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
INFO: Using default notebook: file:///home/cheese/Notebooks/Notes
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Operational error, init tabels
DEBUG: (Re-)Initializing database for index
DEBUG: Opening notebook: <zim.notebook.notebook.Notebook object at 0x7f89bb542750>
DEBUG: Loading config from: <ConfigFile: /home/cheese/.config/zim/preferences.conf>
DEBUG: Loading plugin: calendar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: trayicon
DEBUG: Gtk version is (2, 24, 31)
DEBUG: Pygtk version is (2, 24, 0)
DEBUG: Loading config from: <ConfigFile: /home/cheese/.config/zim/style.conf>
DEBUG: Loading config from: /home/cheese/.cache/zim/notebook-home_cheese_Notebooks_Notes/state.conf
/home/cheese/zim-desktop-wiki/zim/plugins/__init__.py:762: GtkWarning: Inserting action group 'MainWindowExtension' into UI manager which already has a group with this name

  self.window.uimanager.insert_action_group(actiongroup, 0)
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89bbdee090>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Add window: AppIndicatorTrayIcon
DEBUG: Accelmap: /home/cheese/.config/zim/accelmap
INFO: Accelerator changed for <Actions>/PageView/toggle_format_emphasis
INFO: Open page: Home (Home)
DEBUG: Found template 'Default' for Home
INFO: Loading template from: /home/cheese/zim-desktop-wiki/data/templates/wiki/Default.txt
DEBUG: Opening ProgressDialog: Updating index
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /home/cheese/Notebooks/Notes
DEBUG: Index file: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: show_preferences
DEBUG: Loading description for plugin: arithmetic
DEBUG: Opening dialog "Preferences - Zim"
DEBUG: Loading description for plugin: trayicon
DEBUG: Opening dialog "Configure Plugin - Zim"
DEBUG: Dialog response OK
DEBUG: Wrote /home/cheese/.config/zim/preferences.conf
DEBUG: Add window: StatusIconTrayIcon
DEBUG: Remove window: AppIndicatorTrayIcon
DEBUG: Closed dialog "Configure Plugin"
DEBUG: Dialog response OK
DEBUG: Wrote /home/cheese/.config/zim/style.conf
DEBUG: Wrote /home/cheese/.config/zim/preferences.conf
DEBUG: Closed dialog "Preferences"
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c4f6a3d0>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594210>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list

DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594490>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Action: close (delete-event)

DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594810>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594b10>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594e10>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c85aa150>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c85aa450>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c85aa750>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594dd0>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594e50>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list
INFO: Spawning: ['/usr/bin/python', '/home/cheese/zim-desktop-wiki/zim.py', '--gui', 'file:///home/cheese/Notebooks/Notes', '--standalone', '-D'] (cwd: None)
DEBUG: Process started with PID: 3404
INFO: This is zim 0.66
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: No bzr version-info found
DEBUG: Running from a source dir: /home/cheese/zim-desktop-wiki
DEBUG: Set XDG_DATA_HOME to /home/cheese/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/kde-settings/kde-profile/default/share>, <Dir: /usr/local/share>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/cheese/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg>, <Dir: /usr/share/kde-settings/kde-profile/default/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/cheese/.cache
DEBUG: Registered object line
DEBUG: Starting standalone process
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim
DEBUG: Opening notebook: <zim.notebook.notebook.Notebook object at 0x7f7670587550>
DEBUG: Loading config from: <ConfigFile: /home/cheese/.config/zim/preferences.conf>
DEBUG: Loading plugin: calendar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: trayicon
DEBUG: Gtk version is (2, 24, 31)
DEBUG: Pygtk version is (2, 24, 0)
DEBUG: Loading config from: <ConfigFile: /home/cheese/.config/zim/style.conf>
DEBUG: Loading config from: /home/cheese/.cache/zim/notebook-home_cheese_Notebooks_Notes/state.conf
/home/cheese/zim-desktop-wiki/zim/plugins/__init__.py:762: GtkWarning: Inserting action group 'MainWindowExtension' into UI manager which already has a group with this name

  self.window.uimanager.insert_action_group(actiongroup, 0)
DEBUG: Add window: StatusIconTrayIcon
DEBUG: Accelmap: /home/cheese/.config/zim/accelmap
INFO: Accelerator changed for <Actions>/PageView/toggle_format_emphasis
ERROR: Exception in main()
Traceback (most recent call last):
  File "/home/cheese/zim-desktop-wiki/zim/main/__init__.py", line 778, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/home/cheese/zim-desktop-wiki/zim/main/__init__.py", line 566, in run
    self._run_cmd(cmd, args) # test seam
  File "/home/cheese/zim-desktop-wiki/zim/main/__init__.py", line 588, in _run_cmd
    self._run_main_loop(cmd)
  File "/home/cheese/zim-desktop-wiki/zim/main/__init__.py", line 629, in _run_main_loop
    w = cmd.run()
  File "/home/cheese/zim-desktop-wiki/zim/main/__init__.py", line 250, in run
    gui.run()
  File "/home/cheese/zim-desktop-wiki/zim/gui/__init__.py", line 400, in run
    self.open_page(self._first_page)
  File "/home/cheese/zim-desktop-wiki/zim/actions.py", line 132, in func
    self.func(instance, *args, **kwargs)
  File "/home/cheese/zim-desktop-wiki/zim/gui/__init__.py", line 735, in open_page
    self.notebook.index.touch_current_page_placeholder(path)
  File "/home/cheese/zim-desktop-wiki/zim/notebook/index/__init__.py", line 257, in touch_current_page_placeholder
    (ROOT_ID,)
OperationalError: database is locked
DEBUG: Running ErrorDialog
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f766f3bff90>
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim                                                        
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list                                                                         
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f89c8594b50>                                         
DEBUG: Loading config from: /home/cheese/Notebooks/Notes/notebook.zim                                                        
DEBUG: Wrote /home/cheese/.config/zim/notebooks.list

**Comment by cheese** [comment]
That seems an issue only with '--standalone'.

**Comment by jaap-karssenberg** [comment]
Afraid nothing I can do to resolve this issue. Closing for now - please re-open if this occurs on the to be released version 0.70 or later.
