### ISSUE TITLE
Invalid date format in task: <2018-12

### ISSUE THREAD

**Issue by nelas** [jaap-karssenberg/zim-desktop-wiki#585]
Hi, I'm getting this warning in the latest master commit: 425395d3

    ./zim.py --verbose --debug

    [ ] Testing task <2017-12

    WARNING: Invalid date format in task: <2018-12

It's not recognizing December (12) as a valid month due date. If I change to another month (e.g. November) or set a specific day, it works.

**Comment by jaap-karssenberg** [comment]
Fixed in f92698459ea3b43474ed023a0d0a761fbc5d9715 -- thanks for reporting!
