### ISSUE TITLE
Double title bar and offset cursor in Zim 0.69 on MacOS Mohave

### ISSUE THREAD

**Issue by reagle** [jaap-karssenberg/zim-desktop-wiki#587]
While attempting to test zim 0.70, my 0.69 broke. There is now an extra title bar and the mouse cursor is now offset by (I believe) the height of the inner title bar. this is the same issue as another GTK+ app on Mac: geany/geany#1729 and geany/geany#1372.

<img width="902" alt="screen shot 2018-12-21 at 3 45 41 pm" src="https://user-images.githubusercontent.com/596814/50362885-80937b80-0537-11e9-840f-c7844ea5a716.png">

**Comment by Osndok** [comment]
I imagine that this is a gtk3/gtk+ issue (as opposed to zim/geany). Have you tried the 'brew' commands in that thread? or the 'brew upgrade', or 'brew reinstall' commands for those packages?

**Comment by reagle** [comment]
This was Zim 0.69 (with Python2). I've tried all of that but I'm having difficulty getting either zim to work now. In any case, I understand if you close out <0.69 at some point to focus on >=0.70. (I'm going to send a few 0.70 reports soon.)

**Comment by reagle** [comment]
I've been able to mitigate by moving my 0.69 zim to a virtualenv, as I [describe here](https://reagle.org/joseph/zwiki/Archives/2015/Zim_on_Mac_OSX.html).
