### ISSUE TITLE
Zim 0.70 on MacOS Mojave: Can't open source

### ISSUE THREAD

**Issue by reagle** [jaap-karssenberg/zim-desktop-wiki#595]
Because I can't paste into Zim anymore, I thought I'd do a paste in the source file. `Tools / Edit Source` causes the following error.

```
This is zim 0.70
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 7, 2, 'final', 0)
PyGObject: (3, 30, 4)
No bzr version-info found

======= Traceback =======
  File "/Users/reagle/bin/zim-desktop-wiki-master/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/Users/reagle/bin/zim-desktop-wiki-master/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/Users/reagle/bin/zim-desktop-wiki-master/zim/gui/uiactions.py", line 367, in edit_page_source
    edit_file(self.widget, self.page.source, istextfile=True)
  File "/Users/reagle/bin/zim-desktop-wiki-master/zim/gui/applications.py", line 653, in edit_file
    app = AddApplicationDialog(window, 'text/plain').run()
NameError: name 'window' is not defined
```

**Comment by reagle** [comment]
I believe this is related to #589 as this problem also occurred in earlier versions of zim for me as well. Passing --geometry 900x1000-0-0 seems to cause the problem. Perhaps these bugs should be collapsed into a geometry bug.

**Comment by jaap-karssenberg** [comment]
Nope, this has nothing to do with geometry

**Comment by reagle** [comment]
My suspicion may be wrong, but the issue still exists. Not sure why it is closed. Is this related to another issue?

**Comment by jaap-karssenberg** [comment]
If you are using the master branch and up to date with 03bd1b0 the exact same issue can not occur anymore

**Comment by reagle** [comment]
Okay, pulled master and bug is fixed. Thanks!
