### ISSUE TITLE
AttributeError: 'LocalFile' object has no attribute 'isdir'

### ISSUE THREAD

**Issue by Osndok** [jaap-karssenberg/zim-desktop-wiki#61]
File "zim-desktop-wiki/zim/fs.py", line 836, in rename
    if newpath.isdir():

**Comment by jaap-karssenberg** [comment]
What action triggered the error ?

**Comment by Osndok** [comment]
The rename() function was called directly from my modified screenshot plugin.

https://github.com/Osndok/zim-plugin-screenshot2/blob/master/screenshot.py#L203

The exception occurs as it is trying to process the captured image.

**Comment by jaap-karssenberg** [comment]
Yes, you should do something like `imgfile = File(imgfile.path)` to cast to a compatible object.

Reason is that we are migrating from old "fs.py" to new "newfs/..." module. Here you see a crack between two calls using different module.

**Comment by jaap-karssenberg** [comment]
Thinking about it more, maybe better I make the casting automatically in the "fs.py" module. Prevents other cases where this may show up as well.
