### ISSUE TITLE
Clicking on a page function and a feature request

### ISSUE THREAD

**Issue by ClarkeCC** [jaap-karssenberg/zim-desktop-wiki#67]
When clicking on a page that has sub pages they all expand, it annoying to have to collapse them each time because I just want to work on the page I clicked on. If I wanted to see the sub pages I'll click the arrow next to it. Is there a way to disable this function? 

Feature request:

1. Have more option in the toolbar by default like size of font and color. Having the heading option on there by default without having to manual add it.

2. Zim could use a more "modern" look, maybe a redesign on the icon in the toolbar. (Maybe also rename them to bold, italics, underline, ect)

3. Not sure if this is just not possible but sometimes i want a word to be both bold with italics and underline, but I can't for some reason.

4. A box for when writing code.

...

Zim is amazing and has a lot of potential if it gets a new look and more features out of the box, it could be a game changer.
 
Thank you for reading and any help on the question will be appreciated.

**Comment by jaap-karssenberg** [comment]
Sorry, but can't handle multiple request in a single issue - please file one issue per topic
