### ISSUE TITLE
Segmentation fault when opening file or folder by external application

### ISSUE THREAD

**Issue by jaap-karssenberg** [jaap-karssenberg/zim-desktop-wiki#7]
New in release 0.66: various segfaults when opening files or folders in external applications from zim

See also:
- https://bugs.launchpad.net/zim/+bug/1681200
- https://bugs.launchpad.net/zim/+bug/1687382
- https://bugs.launchpad.net/zim/+bug/1686738

**Comment by jaap-karssenberg** [comment]
Root cause not understood at this time. 

Specific cases under linux, Gnome 3:
- Opening attachment folder from button in attachment browser crashes - introduced in 1de58d76cfb34e5d00c8609a50c0b815727cb33a
- Opening a file via attachment browser, e.g. image with "eog", crash when viewer closes, present before 1de58d76cfb34e5d00c8609a50c0b815727cb33a
- Opening source with "gedit" via "edit source" in Tools menu does not crash

Code for spawning new applicaitons is in` zim/applications.py`, but no changes in that part since previous release. Not clear what triggers change of behavior.

Commit 1de58d76cfb34e5d00c8609a50c0b815727cb33a is involved somehow, but code review of this commit does not give a pointer - part of the crashes exists before this commit, but it triggers more of them.

May be a variant where crash happens due to file changes by extrenal applicaitons (not started from zim) but this is not yet confirmed by multiple users. If this is the case, that would point in the direction of file monitoring code, but disabling "gio" monitor in `newfs/helpers.py` does not change the behavior.

**Comment by jaap-karssenberg** [comment]
I have tracked down the root cause to the statement `gobject.threads_init()` in `zim/main/__init__.py`. After removing that line I have seen no more segfaults on my linux system.

Will push a patch and update the daily PPA this evening. Anyone who wants to test already please edit and remove the line mentioned manually.

**Comment by 2l00Z** [comment]
Hi, Jaap

I tried the trick with removing gobject.threads_init ()

First I made sure that the crashes still occur in **r871**.
Yes. After opening a file from the Attachment Browser by a third-party application (`png` with `gwenview`) - the crash took place.
Then, as usual, to quickly start the application, I removed old socket-file fom `/tmp/zim -...`.

Then delete `gobject.threads_init ()` `__init.py__` (Line 584)
zim -D 
OK. It starts

I tried again to open the same png file - NO CRASH!
Seems the trick worked. Thanx.

Here are the last lines from debug output:

> INFO: Spawning: ['gwenview', 'file:///home/andy/dox/zim/zim/bugs/zim551_attbr_bckgr.png'] (cwd: None)
> DEBUG: Process started with PID: 17203
> qt5ct: using qt5ct plugin
> QXcbConnection: XCB error: 5 (BadAtom), sequence: 718, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
> Thumbnail for "file:///home/andy/dox/zim/zim/bugs/zim_v439_dialogs.png" does not contain correct image size information
> Could not get a valid KFileMetaInfo instance for "file:///home/andy/dox/zim/zim/bugs/zim_v439_dialogs.png"
> Thumbnail for "file:///home/andy/dox/zim/zim/bugs/zim551_attbr_bckgr.png" does not contain correct image size information
> Could not get a valid KFileMetaInfo instance for "file:///home/andy/dox/zim/zim/bugs/zim551_attbr_bckgr.png"
--

It seems Zim has become more stable - at least start faster.

Thanks again for the work.

openSUSE Leap 42.2, KDE, Zim r871.

**Comment by 2l00Z** [comment]
Also I suggest to add checking and deleting the old socket-file in case Zim was not gracefully closed.

**Comment by jaap-karssenberg** [comment]
> Will push a patch and update the daily PPA this evening. Anyone who wants to test already please edit and remove the line mentioned manually.

Will take a few days longer - without the "threads_init" statement, threads can hang for a long time, so need to design out some of the threading behavior.

**Comment by jaap-karssenberg** [comment]
Believe patch 9af8f1284e44030c80eb89b214d03eb8825e1039 fixes this issue

**Comment by nelas** [comment]
Hi Jaap, I tested the issue described [here](https://bugs.launchpad.net/zim/+bug/1686738) (open page before background check is done) and it no longer happens on `0.66-SNAPSHOT-t201705021639~ubuntu16.04.1`.
