### ISSUE TITLE
Underlining Headings

### ISSUE THREAD

**Issue by jmoseman01** [jaap-karssenberg/zim-desktop-wiki#71]
In windows 10 I can't underline headings.  I want to provide emphasis to core concepts/keywords in my note's headings but can't currently.

**Comment by Osndok** [comment]
AFAIK, Zim's markup does not overlap styles, and I suspect this is unlikely to change. This can be seen by trying make something bold & underline, for example.

Personally, I like the simplified formatting model, and only rarely find cases that it is disruptive (like striking out text that contains a pagelink).

I do notice that there *is* one headline size that is underlined (header one), and one that is italic (header three), so maybe H1 would work for you? If not, maybe there is a stylesheet that can be tweaked.

**Comment by jaap-karssenberg** [comment]
As Osndok mentioned this is expected behavior, formatting is exclusive in zim
