### ISSUE TITLE
Zim 67~rc1 crashes as soon as Spell Check is turned on

### ISSUE THREAD

**Issue by vossenjp** [jaap-karssenberg/zim-desktop-wiki#72]
I just built a brand new Mint-18.1 VM, and installed Zim 0.65.  Then I added the PPA I'd forgotten and installed `zim-0.67~rc1~ubuntu16.04.1` and `python-gtkspellcheck`.  Now, as soon as I click the icon to turn spell check on, Zim crashes.  I tried a purge and re-install, but it did not help.  Since I can't find any other reports of this, I assume I'm doing something stupid again, but I can't see what it is.

In the Plugin dialog box, it says:
* gtkspell - OK
* gtkspell - Failed

My reading of the "More" section seems to say that only one or the other is needed, not both.  My previous Mint-17 VM that had such a problem with 0.66 says the opposite yet works fine again in 0.67~rc1 (per #16):
* gtkspell - Failed
* gtkspell - OK

The "Default Language" section is blank in both.

In Mint-18.1 if I enable spell check on an "empty" page (1 word, header, etc.) it works, but every single non-empty page I've tried crashes immediately.
```
DEBUG: Action: toggle_spellcheck(True)
DEBUG: Spellcheck language: en_US
DEBUG: requesting name for code "en_US"
DEBUG: requesting name for code "en"
DEBUG: requesting name for code "en_CA"
DEBUG: requesting name for code "en_GB"
DEBUG: Action: toggle_spellcheck(False)
INFO: Open page: 2 Reference:git (2 Reference:git)
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: toggle_spellcheck(True)
DEBUG: requesting name for code "en_US"
DEBUG: requesting name for code "en"
DEBUG: requesting name for code "en_CA"
DEBUG: requesting name for code "en_GB"
/usr/lib/python2.7/dist-packages/gtkspellcheck/spellcheck.py:548: GtkWarning: /build/gtk+2.0-KsZKkB/gtk+2.0-2.24.30/gtk/gtktextbtree.c:4096: char offset off the end of the line
  end = self._buffer.get_iter_at_line_offset(start.get_line(), match.end())

(zim:20939): Gtk-ERROR **: Char offset 82 is off the end of the line
Trace/breakpoint trap
```

Just in case it was cruft in my config I tried this, but no change:
```
$ rm -rf .config/zim .cache/zim .local/share/zim /tmp/zim-jp

$ zim --debug
INFO: This is zim 0.66
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: No bzr version-info found
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/jp/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/cinnamon>, <Dir: /usr/share/gnome>, <Dir: /usr/local/share>, <Dir: /usr/share>, <Dir: /usr/share/mdm>]
DEBUG: Set XDG_CONFIG_HOME to /home/jp/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-cinnamon>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/jp/.cache
DEBUG: Connecting to /tmp/zim-jp/primary-0.66-e63203e4
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Registered object line
WARNING: Could not find all icon sizes for the application icon
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-jp/primary-0.66-e63203e4
DEBUG: First time usage - prompt for notebook folder
DEBUG: Opening dialog "Add Notebook - Zim"
DEBUG: Opening dialog "Select Folder - Zim"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Select Folder"
DEBUG: Loading config from: /home/jp/.../Zim/notebook.zim
DEBUG: Dialog response OK
DEBUG: Closed dialog "Add Notebook"
DEBUG: Loading config from: /home/jp/.../Zim/notebook.zim
DEBUG: Wrote /home/jp/.../Zim/notebook.zim
DEBUG: Wrote /home/jp/.config/zim/notebooks.list
DEBUG: Loading config from: /home/jp/.../Zim/notebook.zim
DEBUG: Operational error, init tabels
DEBUG: (Re-)Initializing database for index
DEBUG: Opening notebook: <zim.notebook.notebook.Notebook object at 0x7f57e8b72690>
DEBUG: Loading config from: <ConfigFile: /home/jp/.config/zim/preferences.conf>
DEBUG: Loading plugin: calendar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: versioncontrol
INFO: No VCS detected
DEBUG: Gtk version is (2, 24, 30)
DEBUG: Pygtk version is (2, 24, 0)
DEBUG: Loading config from: <ConfigFile: /home/jp/.config/zim/style.conf>
DEBUG: Loading config from: /home/jp/.cache/zim/.../state.conf
DEBUG: Accelmap: /home/jp/.config/zim/accelmap
INFO: Open page: Home (Home)
DEBUG: Opening ProgressDialog: Updating index
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /home/jp/.../Zim
... lots of indexing
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
INFO: Open page: 1 Work (1 Work)
DEBUG: Insert object: <zim.gui.pageview.LineObject object at 0x7f57e493f1d0>
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: show_preferences
DEBUG: Loading description for plugin: arithmetic
DEBUG: Opening dialog "Preferences - Zim"
DEBUG: Loading plugin: spell
INFO: Accelerator changed for <Actions>/MainWindowExtension/toggle_spellcheck
DEBUG: Wrote /home/jp/.config/zim/preferences.conf
DEBUG: Loading description for plugin: spell
DEBUG: Dialog response OK
DEBUG: Wrote /home/jp/.config/zim/style.conf
DEBUG: Wrote /home/jp/.config/zim/preferences.conf
DEBUG: Closed dialog "Preferences"
DEBUG: Action: toggle_spellcheck(True)
DEBUG: Spellcheck language: en_US
DEBUG: requesting name for code "en_US"
DEBUG: requesting name for code "en"
DEBUG: requesting name for code "en_CA"
DEBUG: requesting name for code "en_GB"
/usr/lib/python2.7/dist-packages/gtkspellcheck/spellcheck.py:548: GtkWarning: /build/gtk+2.0-KsZKkB/gtk+2.0-2.24.30/gtk/gtktextbtree.c:4096: char offset off the end of the line
  end = self._buffer.get_iter_at_line_offset(start.get_line(), match.end())

(zim:19690): Gtk-ERROR **: Char offset 40 is off the end of the line
Trace/breakpoint trap
```

This is a fully up-to-date Mint-18.1 VM I installed today.  It has the following "spell" packages:
```
aspell-0.60.7~20110707-3build1
aspell-en-7.1-0-1.1
dictionaries-common-1.26.3
enchant-1.6.0-10.1build2
geany-plugin-spellcheck-1.27+dfsg-2
hunspell-en-us-20070829-6ubuntu3
libaspell15:amd64-0.60.7~20110707-3build1
libenchant1c2a:amd64-1.6.0-10.1build2
libgtkspell0-2.0.16-1.1ubuntu1
libhunspell-1.3-0:amd64-1.3.3-4ubuntu1
python-enchant-1.6.6-2
python-gtkspellcheck-3.0-1.1
```

FWIW, Geany spellcheck works fine so far...

**Comment by jaap-karssenberg** [comment]
Afraid this is an error happening in the gtkspellcheck module, not in zim, so can't do much about it

Might already be an issue for this in the gtkspellcheck repository ?

**Comment by vossenjp** [comment]
OK, bottom line up front, the solution for me to get spell checking to not crash Zim 0.67~rc1 on Mint-18.1 (Ubuntu 16.04 LTS Xenial Xerus) is to install a newer package from Zesty, then restart Zim:
```
$ wget http://mirrors.kernel.org/ubuntu/pool/universe/p/pygtkspellcheck/python-gtkspellcheck_4.0.5-1_all.deb
$ sudo dpkg -i python-gtkspellcheck_4.0.5-1_all.deb
```

See also: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python-gtkspellcheck&searchon=names

I'd argue that a problem in a library should not **crash** Zim, but I don't know enough Python to know if it's feasible to "try..except" or whatever at that level.

As far as I can tell, this will affect anyone using Ubuntu 16.04 LTS (Xenial Xerus) and derivatives, like Mint-18, so I'm surprised there are not more reports, but perhaps not many are using the PPA.  Other tools are including `gtkspellcheck` BECAUSE of this bug, perhaps Zim could/should too:
1. https://www.ubuntuupdates.org/package/getdeb_apps/yakkety/apps/getdeb/rednotebook
	1. https://bugs.launchpad.net/rednotebook/+bug/1615629
1. https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages

For the record, over many hours I tried a number of things that did not work.  There are a bunch of references for this problem that I failed to find originally until Jaap got me looking in the right direction.  They include:
* https://bugs.launchpad.net/zim/+bug/1598830
	* https://bugs.launchpad.net/zim/+bug/1598138
* https://www.mail-archive.com/zim-wiki@lists.launchpad.net/msg03936.html
	* FAILED to help `sudo aptitude install libgtkspell3-3-0`
* https://github.com/koehlma/pygtkspellcheck/issues/29
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830509
	* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834405
		* And back to https://github.com/koehlma/pygtkspellcheck/issues/29
* https://bugs.launchpad.net/ubuntu/+source/zim/+bug/1573923
	* https://launchpad.net/~koehlma/+archive/ubuntu/packages/+packages
		* FAILED to help:
			* `wget https://launchpad.net/~koehlma/+archive/ubuntu/packages/+files/python-gtkspellcheck_4.0a-1_all.deb https://launchpad.net/~koehlma/+archive/ubuntu/packages/+files/python3-gtkspellcheck_4.0a-1_all.deb`
			* `sudo dpkg -i /tmp/python-gtkspellcheck_4.0a-1_all.deb /tmp/python3-gtkspellcheck_4.0a-1_all.deb`

I found some solutions recommending upgrading `pygtkspellcheck` via `pip` and that might have worked, but I really, really hate going outside the package system; that always ends in tears sooner or later.  I would have considered doing that in a Python virtual environment, but I have no idea how to get Zim to run in something like that.  A "frozen" virtenv might be something to consider for the future though, to mitigate problems like this.
