### ISSUE TITLE
Spell-checking language resets after restart

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#74]
After manually closing and launching Zim, the chosen spell-checking language is always reseted to the default one, mentioned in the plugin's settings. Ideally, the chosen spell-checking language should be saved.

**Comment by jaap-karssenberg** [comment]
As of 0.70 this will be a notebook property. In my testing it is stored. Please open a new issue if similar problems are seen for the to be released zim 0.70 or newer.

**Comment by jaap-karssenberg** [comment]
Yes, it became a property - see the notebook properties in the File menu

**Comment by sojusnik** [comment]
Found it! It was tricky to find the proper format for the language (f.i. en_US or de_AT). It would certainly help, especially for non-tech-savvy users, to mention it there!
