### ISSUE TITLE
Rich Text

### ISSUE THREAD

**Issue by ClarkeCC** [jaap-karssenberg/zim-desktop-wiki#75]
Would include:

1. Change color of text.

2. Change color of highlight. (Foreground color, background color)

3. Size of text.

4. Possibility to use bold/italics/underline/highlight/ underline/strikethrough together if needed.

**Comment by Osndok** [comment]
At some point, it would probably be easier to simply swap-in an alternative wiki syntax (like markdown, textile, or docuwiki).

**Comment by ClarkeCC** [comment]
Yeah the current wiki syntax is just too simple.

**Comment by e3rd** [comment]
(Oh, please, let's go to markdown :) )

**Comment by ClarkeCC** [comment]
Could use http://slatejs.org/#/rich-text

**Comment by jaap-karssenberg** [comment]
Full rich text support is "won't fix" for me

Markdown support is on my list, but be aware that pure markdown will also not support things like text colors

**Comment by lrq3000** [comment]
simple markdown would be AWESOME!!! (even though I secretly hope for multimarkdown support sometime in the future, mainly for citations, biblio & footnotes support ;) )

**Comment by chappy721** [comment]
at least different text colors or background colors would be fine.

My question: would it be a possibility to develop an addon for this?
If yes, I could donate for this addon.

Thanks
Daniel
