### ISSUE TITLE
Supporting several programming languages

### ISSUE THREAD

**Issue by ClarkeCC** [jaap-karssenberg/zim-desktop-wiki#76]
With syntax highlighting if possible.

**Comment by Osndok** [comment]
I assume you are referring to a "code block"?

I know that the diagram editor pulls in a syntax-highlighting line-enumerating editor... so this probably would not be too hard to do...

**Comment by ClarkeCC** [comment]
@Osndok yes, a dedicated code box would be great.

**Comment by jaap-karssenberg** [comment]
Please check the "source view" plugin

**Comment by ClarkeCC** [comment]
Oh okay thank you!
