### ISSUE TITLE
Text cursor after pictures

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#79]
The width of a text cursor after a picture is proportional to the size of the picture. So a large picture has a wider text cursor, than a small one, like shown [here](https://mega.nz/#!G4xmWaxQ!uUFixYc1tevPG-Jf4R4atTawx8JUeht-YH-4hZ_ScEU).

Would be nice to have always the same text cursor width, regardless of the picture size.

**Comment by jaap-karssenberg** [comment]
Can't change that, Gtk behavior
