### ISSUE TITLE
Undo/redo keyboard shortcuts stop working on Cyrillic keyboard layout

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#81]
I mainly use the German keyboard layout with a German keyboard. Therefore my keyboard shortcuts for undo are "Ctrl+Z" and "Shift+Ctrl+Z" for redo.
When I change to the Cyrillic keyboard layout, then those two shortcuts stop to work, although other Zim shortcuts still work well.
After playing a little bit around, I realized, that when changing the undo keyboard shortcut by means of `gsettings set org.gnome.desktop.interface can-change-accels true` (run in the terminal) with the Cyrillic keyboard layout, then Zim inexplicably identifies the keystroke combination "Ctrl+Z" as "Ctrl+H", when highlighting the undo menu entry with the mouse and pressing "Ctrl+Z" on the keyboard.

Could you kindly have a look on that?

**Comment by jaap-karssenberg** [comment]
Afraid that is not something I can change from zim, seems more generic item with your keyboard setup in Gtk. Would expect same behavior happens with other Gtk applications as well.

**Comment by sojusnik** [comment]
Any clue where I can report this?

**Comment by jaap-karssenberg** [comment]
I would start by asking help at the generic Gtk help mailing list or IRC channel, but I'm not active myself at those places, so not sure what is best.

**Comment by jaap-karssenberg** [comment]
Closing this item for now. With release 0.70 we use Gtk3 and probably situation is different due to changes in underlying libraries. Please open a new ticket if seen in the to be released 0.70 version or newer.

**Comment by sojusnik** [comment]
Happens even with v0.70 :/

**Comment by sojusnik** [comment]
> Please open a new ticket if seen in the to be released 0.70 version or newer.

Do you really want to have a new ticket on that or are new comments enough?

**Comment by sojusnik** [comment]
Maybe you can add a "undo_alt1" shortcut, like we already have with "redo_alt1" as a workaround for that? This could also be helpful for [this](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/890) issue.

**Comment by jaap-karssenberg** [comment]
Would not like to have a generic ^H keybinding for undo. I think above
issue is but easier already since we now have keybinding changes via the
preferences menu.

-- Jaap
