### ISSUE TITLE
H5 is italic

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#82]
I'm using the latest 0.66 version from the snapshots repository and observe, that [h5 is italic](http://i.imgur.com/x70k2Ul.png), although not configured that way:

`~/.config/zim/style.conf ` contains:
```
[Tag h5]
foreground=#A78900
scale=1.1
weight=PANGO_WEIGHT_BOLD
```
`/usr/share/zim/style.conf` contains:
```
[Tag h5]
foreground=#4e9a06
weight=PANGO_WEIGHT_BOLD
```
Any ideas why?

**Comment by jaap-karssenberg** [comment]
Because the default is hardcoded in the code and the config file does not explicitly set a different style.

If you want to change it you can specificy "`style=PANGO_STYLE_NORMAL`" to remove the italic formatting.
