### ISSUE TITLE
ServerProxy alternative

### ISSUE THREAD

**Issue by e3rd** [jaap-karssenberg/zim-desktop-wiki#83]
In the last version of zim, ipc.py had ServerProxy class.  
I add text to zim page through plugin command. However, when the page being altered is open, I should call `ui.reload_page()` so that the user sees immediately the new text. If I don't reload, text won't appear and when user changes page, an error reporting about concurrent modification of file is displayed.

I used to obtain ui object from ServerProxy like this:

```python
start_server_if_not_running()
server = ServerProxy()            
ui = server.get_notebook(self.get_notebook_argument()[0].uri, False)
reload = (lambda: ui.reload_page()) if ui else lambda: None # if Zim is currently open
ntb, _ = self.build_notebook()
reload() # save current user's work, if zim's open
GoogletasksController(notebook = ntb).fetch() # add new lines
reload() # save new lines       
```

I've done a thorough search but found now alternative. Could somebody please help me by a small hint?  
Thanks a lot!

**Comment by Osndok** [comment]
I have no idea if it is the correct way, but you might be interested in how I worked around this change here:
* https://github.com/Osndok/zim-plugin-append/commit/ffefa818f7a6f9583b9d75562cbea2abdde8036e

**Comment by jaap-karssenberg** [comment]
Would help if you give a bit more context of what you try to do. I would not expect a plugin to ever need the remote call.

**Comment by e3rd** [comment]
Thank you, Osndok, the example from append plugin really helped me! Now, I understand new Zim IPC much better, really thanks :)

(Jaap, this was because of a (Googletasks plugin)[https://github.com/e3rd/zim-plugin-googletasks/] that fetches the tasks from remote Google server to the Home page. This can be done manually via menu or automatically via an anacron script that keeps me sure I have the fresh tasks loaded every day. However, when anacron launched the plugin cli a fetched the tasks in the background while I was simultaneously browsing the Zim at the Home page, the freshly-fetched text wouldn't appear immediately. So that the cli has to dispatch `reload_ui()` remote call, I didn't invent better way.)

Wish you the best, Edvard

**Comment by jaap-karssenberg** [comment]
My recommendation would be that the plugin defines a "GtkCommand" subclass that does the refresh and any other actions you want to do. As in the example you can access the windows via the application object (bit of a hack as it is a private argument, but best way for now I guess).

Now remote you can call "zim --plugin yourplugin" followed by any options for your plugin. The command will be called in the main process without need to do any ipc explicitly. Zim will internally do the ipc call for you.

**Comment by e3rd** [comment]
Yes yes, I implemented it just like you say :) Zim is really great that we can extend it in many ways. In comparison with OneNote where some features would never be implemented.
