### ISSUE TITLE
interwiki names in urls.list 

### ISSUE THREAD

**Issue by ecodiv** [jaap-karssenberg/zim-desktop-wiki#9]
I have a list of pre-defined urls in "~/.local/share/zim/urls.list", but this doesn't work any more after the update to 0.6. 

> This is zim 0.66
> Platform: posix
> Locale: en_US UTF-8
> FS encoding: UTF-8
> Python: (2, 7, 12, 'final', 0)
> Gtk: (2, 24, 30)
> Pygtk: (2, 24, 0)
> No bzr version-info found
> 
> ======= Traceback =======
>   File "/home/paulo/Software/Linux/zim-desktop-wiki/zim/gui/pageview.py", line 5575, in do_link_clicked
>     self.ui.open_notebook(uri, pagename)
> UnboundLocalError: local variable 'pagename' referenced before assignment

Note that the interwiki terms do work if defined in the .zim file of the zim  notebook.

**Comment by jaap-karssenberg** [comment]
Patch in 18bfe1e10844dfe61eb5930264488d994bb4e5df
