### ISSUE TITLE
[Tray Icon] Icon does not scale with panel

### ISSUE THREAD

**Issue by sphh** [jaap-karssenberg/zim-desktop-wiki#97]
If I change the panel, the tray icon does not honour the changed panel size and stays the same. Every other indicator icon changes its size to fill the available size of the panel.

Zim v0.66

**Comment by jaap-karssenberg** [comment]
Afraid this is a "won't fix" as this is handled by the libraries, not zim itself

**Comment by sphh** [comment]
Thank you for looking into it.

Could you please tell me which library is responsible (that would save me a lot of time to dig into the code) so that I can file the bug report there.

Thanks.
